// Code generated by ent, DO NOT EDIT.

package dzoorganization

import (
	"time"

	"encore.app/db/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldLTE(FieldID, id))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldClientID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldName, v))
}

// ShortName applies equality check predicate on the "short_name" field. It's identical to ShortNameEQ.
func ShortName(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldShortName, v))
}

// Bin applies equality check predicate on the "bin" field. It's identical to BinEQ.
func Bin(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldBin, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldUpdatedAt, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v uuid.UUID) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldLTE(FieldClientID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldContainsFold(FieldName, v))
}

// ShortNameEQ applies the EQ predicate on the "short_name" field.
func ShortNameEQ(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldShortName, v))
}

// ShortNameNEQ applies the NEQ predicate on the "short_name" field.
func ShortNameNEQ(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNEQ(FieldShortName, v))
}

// ShortNameIn applies the In predicate on the "short_name" field.
func ShortNameIn(vs ...string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldIn(FieldShortName, vs...))
}

// ShortNameNotIn applies the NotIn predicate on the "short_name" field.
func ShortNameNotIn(vs ...string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNotIn(FieldShortName, vs...))
}

// ShortNameGT applies the GT predicate on the "short_name" field.
func ShortNameGT(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldGT(FieldShortName, v))
}

// ShortNameGTE applies the GTE predicate on the "short_name" field.
func ShortNameGTE(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldGTE(FieldShortName, v))
}

// ShortNameLT applies the LT predicate on the "short_name" field.
func ShortNameLT(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldLT(FieldShortName, v))
}

// ShortNameLTE applies the LTE predicate on the "short_name" field.
func ShortNameLTE(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldLTE(FieldShortName, v))
}

// ShortNameContains applies the Contains predicate on the "short_name" field.
func ShortNameContains(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldContains(FieldShortName, v))
}

// ShortNameHasPrefix applies the HasPrefix predicate on the "short_name" field.
func ShortNameHasPrefix(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldHasPrefix(FieldShortName, v))
}

// ShortNameHasSuffix applies the HasSuffix predicate on the "short_name" field.
func ShortNameHasSuffix(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldHasSuffix(FieldShortName, v))
}

// ShortNameIsNil applies the IsNil predicate on the "short_name" field.
func ShortNameIsNil() predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldIsNull(FieldShortName))
}

// ShortNameNotNil applies the NotNil predicate on the "short_name" field.
func ShortNameNotNil() predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNotNull(FieldShortName))
}

// ShortNameEqualFold applies the EqualFold predicate on the "short_name" field.
func ShortNameEqualFold(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEqualFold(FieldShortName, v))
}

// ShortNameContainsFold applies the ContainsFold predicate on the "short_name" field.
func ShortNameContainsFold(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldContainsFold(FieldShortName, v))
}

// BinEQ applies the EQ predicate on the "bin" field.
func BinEQ(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldBin, v))
}

// BinNEQ applies the NEQ predicate on the "bin" field.
func BinNEQ(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNEQ(FieldBin, v))
}

// BinIn applies the In predicate on the "bin" field.
func BinIn(vs ...string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldIn(FieldBin, vs...))
}

// BinNotIn applies the NotIn predicate on the "bin" field.
func BinNotIn(vs ...string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNotIn(FieldBin, vs...))
}

// BinGT applies the GT predicate on the "bin" field.
func BinGT(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldGT(FieldBin, v))
}

// BinGTE applies the GTE predicate on the "bin" field.
func BinGTE(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldGTE(FieldBin, v))
}

// BinLT applies the LT predicate on the "bin" field.
func BinLT(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldLT(FieldBin, v))
}

// BinLTE applies the LTE predicate on the "bin" field.
func BinLTE(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldLTE(FieldBin, v))
}

// BinContains applies the Contains predicate on the "bin" field.
func BinContains(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldContains(FieldBin, v))
}

// BinHasPrefix applies the HasPrefix predicate on the "bin" field.
func BinHasPrefix(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldHasPrefix(FieldBin, v))
}

// BinHasSuffix applies the HasSuffix predicate on the "bin" field.
func BinHasSuffix(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldHasSuffix(FieldBin, v))
}

// BinIsNil applies the IsNil predicate on the "bin" field.
func BinIsNil() predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldIsNull(FieldBin))
}

// BinNotNil applies the NotNil predicate on the "bin" field.
func BinNotNil() predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNotNull(FieldBin))
}

// BinEqualFold applies the EqualFold predicate on the "bin" field.
func BinEqualFold(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEqualFold(FieldBin, v))
}

// BinContainsFold applies the ContainsFold predicate on the "bin" field.
func BinContainsFold(v string) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldContainsFold(FieldBin, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasEmployees applies the HasEdge predicate on the "employees" edge.
func HasEmployees() predicate.DzoOrganization {
	return predicate.DzoOrganization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EmployeesTable, EmployeesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEmployeesWith applies the HasEdge predicate on the "employees" edge with a given conditions (other predicates).
func HasEmployeesWith(preds ...predicate.Employee) predicate.DzoOrganization {
	return predicate.DzoOrganization(func(s *sql.Selector) {
		step := newEmployeesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DzoOrganization) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DzoOrganization) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DzoOrganization) predicate.DzoOrganization {
	return predicate.DzoOrganization(sql.NotPredicates(p))
}
