-- create "request_dzo_contracts" table
CREATE TABLE "public"."request_dzo_contracts" (
  "id" uuid NOT NULL,
  "request_id" uuid NOT NULL,
  "dzo_id" uuid NOT NULL,
  "file_name" character varying NOT NULL,
  "file_url" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- create index "requestdzocontract_dzo_id" to table: "request_dzo_contracts"
CREATE INDEX "requestdzocontract_dzo_id" ON "public"."request_dzo_contracts" ("dzo_id");
-- create index "requestdzocontract_request_id" to table: "request_dzo_contracts"
CREATE INDEX "requestdzocontract_request_id" ON "public"."request_dzo_contracts" ("request_id");
-- create index "requestdzocontract_request_id_dzo_id" to table: "request_dzo_contracts"
CREATE UNIQUE INDEX "requestdzocontract_request_id_dzo_id" ON "public"."request_dzo_contracts" ("request_id", "dzo_id");
-- create "request_participants" table
CREATE TABLE "public"."request_participants" (
  "id" uuid NOT NULL,
  "request_id" uuid NOT NULL,
  "employee_id" uuid NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- create index "requestparticipant_employee_id" to table: "request_participants"
CREATE INDEX "requestparticipant_employee_id" ON "public"."request_participants" ("employee_id");
-- create index "requestparticipant_request_id" to table: "request_participants"
CREATE INDEX "requestparticipant_request_id" ON "public"."request_participants" ("request_id");
-- create index "requestparticipant_request_id_employee_id" to table: "request_participants"
CREATE UNIQUE INDEX "requestparticipant_request_id_employee_id" ON "public"."request_participants" ("request_id", "employee_id");
-- create "contract_supplier_histories" table
CREATE TABLE "public"."contract_supplier_histories" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "history_id" uuid NOT NULL,
  "contract_id" uuid NOT NULL,
  "operation_type" character varying NOT NULL,
  "changed_at" timestamptz NOT NULL,
  "changed_by" uuid NULL,
  "snapshot" jsonb NULL,
  "diff" jsonb NULL,
  PRIMARY KEY ("id")
);
-- create index "contract_supplier_histories_history_id_key" to table: "contract_supplier_histories"
CREATE UNIQUE INDEX "contract_supplier_histories_history_id_key" ON "public"."contract_supplier_histories" ("history_id");
-- create index "contract_supplier_history_changed_at" to table: "contract_supplier_histories"
CREATE INDEX "contract_supplier_history_changed_at" ON "public"."contract_supplier_histories" ("changed_at");
-- create index "contract_supplier_history_contract_id" to table: "contract_supplier_histories"
CREATE INDEX "contract_supplier_history_contract_id" ON "public"."contract_supplier_histories" ("contract_id");
-- create "training_participants" table
CREATE TABLE "public"."training_participants" (
  "id" uuid NOT NULL,
  "event_id" uuid NOT NULL,
  "employee_id" uuid NOT NULL,
  "status" character varying NOT NULL,
  "certificate_id" uuid NULL,
  PRIMARY KEY ("id")
);
-- create "dzo_organizations" table
CREATE TABLE "public"."dzo_organizations" (
  "id" uuid NOT NULL,
  "client_id" uuid NOT NULL,
  "name" character varying NOT NULL,
  "short_name" character varying NULL,
  "bin" character varying NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- create "training_events" table
CREATE TABLE "public"."training_events" (
  "id" uuid NOT NULL,
  "title" character varying NOT NULL,
  "start_date" timestamptz NOT NULL,
  "end_date" timestamptz NOT NULL,
  "location_type" character varying NOT NULL,
  "location_city" character varying NULL,
  "category_id" uuid NOT NULL,
  "direction" character varying NULL,
  "dzo_id" uuid NOT NULL,
  "dzo_contract_id" uuid NULL,
  "participants_count" bigint NOT NULL,
  "cost_per_person_vat" double precision NULL,
  "cost_group_vat" double precision NULL,
  "kyu_hourly_rate" double precision NULL,
  "supplier_id" uuid NULL,
  "supplier_contract_id" uuid NULL,
  "supplier_cost_vat" double precision NULL,
  "supplier_cost_currency" double precision NULL,
  "supplier_currency" character varying NULL,
  "local_content_pct" double precision NULL,
  PRIMARY KEY ("id")
);
-- create "request_target_dzos" table
CREATE TABLE "public"."request_target_dzos" (
  "id" uuid NOT NULL,
  "request_id" uuid NOT NULL,
  "dzo_id" uuid NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- create index "requesttargetdzo_dzo_id" to table: "request_target_dzos"
CREATE INDEX "requesttargetdzo_dzo_id" ON "public"."request_target_dzos" ("dzo_id");
-- create index "requesttargetdzo_request_id" to table: "request_target_dzos"
CREATE INDEX "requesttargetdzo_request_id" ON "public"."request_target_dzos" ("request_id");
-- create index "requesttargetdzo_request_id_dzo_id" to table: "request_target_dzos"
CREATE UNIQUE INDEX "requesttargetdzo_request_id_dzo_id" ON "public"."request_target_dzos" ("request_id", "dzo_id");
-- create "organizations" table
CREATE TABLE "public"."organizations" (
  "id" uuid NOT NULL,
  "name" character varying NOT NULL,
  "code" character varying NOT NULL,
  "type" character varying NOT NULL DEFAULT 'subsidiary',
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "parent_id" uuid NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "organizations_organizations_children" FOREIGN KEY ("parent_id") REFERENCES "public"."organizations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- create index "organization_code" to table: "organizations"
CREATE INDEX "organization_code" ON "public"."organizations" ("code");
-- create index "organization_parent_id" to table: "organizations"
CREATE INDEX "organization_parent_id" ON "public"."organizations" ("parent_id");
-- create index "organizations_code_key" to table: "organizations"
CREATE UNIQUE INDEX "organizations_code_key" ON "public"."organizations" ("code");
-- create "employees" table
CREATE TABLE "public"."employees" (
  "id" uuid NOT NULL,
  "client_id" uuid NOT NULL,
  "position" character varying NULL,
  "full_name" character varying NOT NULL,
  "short_name" character varying NULL,
  "department" character varying NULL,
  "direction" character varying NULL,
  "email" character varying NOT NULL,
  "internal_phone" character varying NULL,
  "birth_date" date NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "user_id" uuid NULL,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "dzo_id" uuid NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "employees_dzo_organizations_employees" FOREIGN KEY ("dzo_id") REFERENCES "public"."dzo_organizations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- create "categories" table
CREATE TABLE "public"."categories" (
  "id" uuid NOT NULL,
  "name" character varying NOT NULL,
  "description" character varying NULL,
  PRIMARY KEY ("id")
);
-- create "contract_suppliers" table
CREATE TABLE "public"."contract_suppliers" (
  "id" uuid NOT NULL,
  "supplier_id" uuid NOT NULL,
  "contract_number" character varying NOT NULL,
  "vat_flag" bigint NOT NULL DEFAULT 0,
  "signed_date" date NOT NULL,
  "end_date" date NULL,
  "amount" numeric(14,2) NOT NULL,
  "amount_currency" numeric(14,2) NULL,
  "currency" character varying NULL,
  "balance_at_year_end" numeric(14,2) NULL,
  "amendment_number" character varying NULL,
  "amendment_date" date NULL,
  "amendment_amount" numeric(14,2) NULL,
  "total_with_amendment" numeric(14,2) NOT NULL,
  "remaining_amount" numeric(14,2) NOT NULL,
  "file_key" character varying NULL,
  "file_name" character varying NULL,
  "file_size" bigint NULL,
  "file_mime_type" character varying NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id")
);
-- create index "contract_supplier_contract_number" to table: "contract_suppliers"
CREATE INDEX "contract_supplier_contract_number" ON "public"."contract_suppliers" ("contract_number");
-- create index "contract_supplier_supplier_id" to table: "contract_suppliers"
CREATE INDEX "contract_supplier_supplier_id" ON "public"."contract_suppliers" ("supplier_id");
-- create "suppliers" table
CREATE TABLE "public"."suppliers" (
  "id" uuid NOT NULL,
  "client_id" uuid NOT NULL,
  "type" character varying NOT NULL,
  "name" character varying NOT NULL,
  "bin_or_iin" character varying NULL,
  "local_content_pct" numeric(5,2) NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  PRIMARY KEY ("id")
);
-- create index "supplier_client_id" to table: "suppliers"
CREATE INDEX "supplier_client_id" ON "public"."suppliers" ("client_id");
-- create index "supplier_is_active" to table: "suppliers"
CREATE INDEX "supplier_is_active" ON "public"."suppliers" ("is_active");
-- create index "supplier_type" to table: "suppliers"
CREATE INDEX "supplier_type" ON "public"."suppliers" ("type");
-- create index "suppliers_bin_or_iin_key" to table: "suppliers"
CREATE UNIQUE INDEX "suppliers_bin_or_iin_key" ON "public"."suppliers" ("bin_or_iin");
-- create "clients" table
CREATE TABLE "public"."clients" (
  "id" uuid NOT NULL,
  "name" character varying NOT NULL,
  "domain" character varying NULL,
  "language" character varying NULL,
  "user_limit" bigint NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- create "users" table
CREATE TABLE "public"."users" (
  "id" uuid NOT NULL,
  "keycloak_user_id" character varying NOT NULL,
  "email" character varying NOT NULL,
  "role" character varying NOT NULL DEFAULT 'EMP',
  "dzo_id" uuid NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_onboarded" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "client_id" uuid NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "users_clients_users" FOREIGN KEY ("client_id") REFERENCES "public"."clients" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- create index "user_dzo_id" to table: "users"
CREATE INDEX "user_dzo_id" ON "public"."users" ("dzo_id");
-- create index "user_email" to table: "users"
CREATE INDEX "user_email" ON "public"."users" ("email");
-- create index "users_keycloak_user_id_key" to table: "users"
CREATE UNIQUE INDEX "users_keycloak_user_id_key" ON "public"."users" ("keycloak_user_id");
-- create "external_training_events" table
CREATE TABLE "public"."external_training_events" (
  "id" uuid NOT NULL,
  "name" character varying NOT NULL,
  "format" character varying NULL,
  "capacity" bigint NULL,
  "supplier_cost_vat" double precision NULL,
  "start_date" timestamptz NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  "is_deleted" boolean NOT NULL DEFAULT false,
  "category_id" uuid NULL,
  "contract_id" uuid NOT NULL,
  "supplier_id" uuid NOT NULL,
  "responsible_user_id" uuid NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "external_training_events_categories_external_training_events" FOREIGN KEY ("category_id") REFERENCES "public"."categories" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "external_training_events_contract_suppliers_external_training_e" FOREIGN KEY ("contract_id") REFERENCES "public"."contract_suppliers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "external_training_events_suppliers_external_training_events" FOREIGN KEY ("supplier_id") REFERENCES "public"."suppliers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "external_training_events_users_responsible_external_training_ev" FOREIGN KEY ("responsible_user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL
);
-- create "requests" table
CREATE TABLE "public"."requests" (
  "id" uuid NOT NULL,
  "entity_id" uuid NOT NULL,
  "entity_type" character varying NOT NULL DEFAULT 'TRAINING_EVENT',
  "request_type" character varying NOT NULL DEFAULT 'MAIN',
  "kind" character varying NOT NULL DEFAULT 'REGULAR',
  "assigned_hr_id" uuid NULL,
  "target_dzo_id" uuid NULL,
  "title" character varying NULL,
  "category" character varying NULL,
  "format" character varying NULL,
  "responsible_admin_id" uuid NULL,
  "training_date" timestamptz NULL,
  "deadline_at" timestamptz NULL,
  "cost_amount" double precision NULL,
  "cost_mode" character varying NULL,
  "step" bigint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "completed_at" timestamptz NULL,
  "status" character varying NOT NULL DEFAULT 'DRAFT',
  "replaced_by_request_id" uuid NULL,
  "is_blocked" boolean NOT NULL DEFAULT false,
  "parent_request_id" uuid NULL,
  "initiator_id" uuid NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "requests_requests_children" FOREIGN KEY ("parent_request_id") REFERENCES "public"."requests" ("id") ON UPDATE NO ACTION ON DELETE SET NULL,
  CONSTRAINT "requests_users_requests" FOREIGN KEY ("initiator_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- create index "request_assigned_hr_id" to table: "requests"
CREATE INDEX "request_assigned_hr_id" ON "public"."requests" ("assigned_hr_id");
-- create index "request_entity_id" to table: "requests"
CREATE INDEX "request_entity_id" ON "public"."requests" ("entity_id");
-- create index "request_initiator_id" to table: "requests"
CREATE INDEX "request_initiator_id" ON "public"."requests" ("initiator_id");
-- create index "request_kind" to table: "requests"
CREATE INDEX "request_kind" ON "public"."requests" ("kind");
-- create index "request_parent_request_id" to table: "requests"
CREATE INDEX "request_parent_request_id" ON "public"."requests" ("parent_request_id");
-- create index "request_request_type" to table: "requests"
CREATE INDEX "request_request_type" ON "public"."requests" ("request_type");
-- create index "request_status" to table: "requests"
CREATE INDEX "request_status" ON "public"."requests" ("status");
-- create index "request_step" to table: "requests"
CREATE INDEX "request_step" ON "public"."requests" ("step");
-- create index "request_target_dzo_id" to table: "requests"
CREATE INDEX "request_target_dzo_id" ON "public"."requests" ("target_dzo_id");
