// Code generated by ent, DO NOT EDIT.

package trainingparticipant

import (
	"encore.app/db/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldLTE(FieldID, id))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldEQ(FieldEventID, v))
}

// EmployeeID applies equality check predicate on the "employee_id" field. It's identical to EmployeeIDEQ.
func EmployeeID(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldEQ(FieldEmployeeID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldEQ(FieldStatus, v))
}

// CertificateID applies equality check predicate on the "certificate_id" field. It's identical to CertificateIDEQ.
func CertificateID(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldEQ(FieldCertificateID, v))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldNotIn(FieldEventID, vs...))
}

// EventIDGT applies the GT predicate on the "event_id" field.
func EventIDGT(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldGT(FieldEventID, v))
}

// EventIDGTE applies the GTE predicate on the "event_id" field.
func EventIDGTE(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldGTE(FieldEventID, v))
}

// EventIDLT applies the LT predicate on the "event_id" field.
func EventIDLT(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldLT(FieldEventID, v))
}

// EventIDLTE applies the LTE predicate on the "event_id" field.
func EventIDLTE(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldLTE(FieldEventID, v))
}

// EmployeeIDEQ applies the EQ predicate on the "employee_id" field.
func EmployeeIDEQ(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldEQ(FieldEmployeeID, v))
}

// EmployeeIDNEQ applies the NEQ predicate on the "employee_id" field.
func EmployeeIDNEQ(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldNEQ(FieldEmployeeID, v))
}

// EmployeeIDIn applies the In predicate on the "employee_id" field.
func EmployeeIDIn(vs ...uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldIn(FieldEmployeeID, vs...))
}

// EmployeeIDNotIn applies the NotIn predicate on the "employee_id" field.
func EmployeeIDNotIn(vs ...uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldNotIn(FieldEmployeeID, vs...))
}

// EmployeeIDGT applies the GT predicate on the "employee_id" field.
func EmployeeIDGT(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldGT(FieldEmployeeID, v))
}

// EmployeeIDGTE applies the GTE predicate on the "employee_id" field.
func EmployeeIDGTE(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldGTE(FieldEmployeeID, v))
}

// EmployeeIDLT applies the LT predicate on the "employee_id" field.
func EmployeeIDLT(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldLT(FieldEmployeeID, v))
}

// EmployeeIDLTE applies the LTE predicate on the "employee_id" field.
func EmployeeIDLTE(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldLTE(FieldEmployeeID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldContainsFold(FieldStatus, v))
}

// CertificateIDEQ applies the EQ predicate on the "certificate_id" field.
func CertificateIDEQ(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldEQ(FieldCertificateID, v))
}

// CertificateIDNEQ applies the NEQ predicate on the "certificate_id" field.
func CertificateIDNEQ(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldNEQ(FieldCertificateID, v))
}

// CertificateIDIn applies the In predicate on the "certificate_id" field.
func CertificateIDIn(vs ...uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldIn(FieldCertificateID, vs...))
}

// CertificateIDNotIn applies the NotIn predicate on the "certificate_id" field.
func CertificateIDNotIn(vs ...uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldNotIn(FieldCertificateID, vs...))
}

// CertificateIDGT applies the GT predicate on the "certificate_id" field.
func CertificateIDGT(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldGT(FieldCertificateID, v))
}

// CertificateIDGTE applies the GTE predicate on the "certificate_id" field.
func CertificateIDGTE(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldGTE(FieldCertificateID, v))
}

// CertificateIDLT applies the LT predicate on the "certificate_id" field.
func CertificateIDLT(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldLT(FieldCertificateID, v))
}

// CertificateIDLTE applies the LTE predicate on the "certificate_id" field.
func CertificateIDLTE(v uuid.UUID) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldLTE(FieldCertificateID, v))
}

// CertificateIDIsNil applies the IsNil predicate on the "certificate_id" field.
func CertificateIDIsNil() predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldIsNull(FieldCertificateID))
}

// CertificateIDNotNil applies the NotNil predicate on the "certificate_id" field.
func CertificateIDNotNil() predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.FieldNotNull(FieldCertificateID))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TrainingParticipant) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TrainingParticipant) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TrainingParticipant) predicate.TrainingParticipant {
	return predicate.TrainingParticipant(sql.NotPredicates(p))
}
