// Code generated by ent, DO NOT EDIT.

package category

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the category type in the database.
	Label = "category"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeExternalTrainingEvents holds the string denoting the external_training_events edge name in mutations.
	EdgeExternalTrainingEvents = "external_training_events"
	// Table holds the table name of the category in the database.
	Table = "categories"
	// ExternalTrainingEventsTable is the table that holds the external_training_events relation/edge.
	ExternalTrainingEventsTable = "external_training_events"
	// ExternalTrainingEventsInverseTable is the table name for the ExternalTrainingEvent entity.
	// It exists in this package in order to avoid circular dependency with the "externaltrainingevent" package.
	ExternalTrainingEventsInverseTable = "external_training_events"
	// ExternalTrainingEventsColumn is the table column denoting the external_training_events relation/edge.
	ExternalTrainingEventsColumn = "category_id"
)

// Columns holds all SQL columns for category fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Category queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByExternalTrainingEventsCount orders the results by external_training_events count.
func ByExternalTrainingEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newExternalTrainingEventsStep(), opts...)
	}
}

// ByExternalTrainingEvents orders the results by external_training_events terms.
func ByExternalTrainingEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExternalTrainingEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newExternalTrainingEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExternalTrainingEventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ExternalTrainingEventsTable, ExternalTrainingEventsColumn),
	)
}
