// Code generated by ent, DO NOT EDIT.

package dzopositiontitle

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the dzopositiontitle type in the database.
	Label = "dzo_position_title"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDzoID holds the string denoting the dzo_id field in the database.
	FieldDzoID = "dzo_id"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldGeneralPositionID holds the string denoting the general_position_id field in the database.
	FieldGeneralPositionID = "general_position_id"
	// FieldLocalTitle holds the string denoting the local_title field in the database.
	FieldLocalTitle = "local_title"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldIsDeleted holds the string denoting the is_deleted field in the database.
	FieldIsDeleted = "is_deleted"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeDzo holds the string denoting the dzo edge name in mutations.
	EdgeDzo = "dzo"
	// EdgeGeneralPosition holds the string denoting the general_position edge name in mutations.
	EdgeGeneralPosition = "general_position"
	// EdgeEmployees holds the string denoting the employees edge name in mutations.
	EdgeEmployees = "employees"
	// Table holds the table name of the dzopositiontitle in the database.
	Table = "dzo_position_titles"
	// DzoTable is the table that holds the dzo relation/edge.
	DzoTable = "dzo_position_titles"
	// DzoInverseTable is the table name for the DzoOrganization entity.
	// It exists in this package in order to avoid circular dependency with the "dzoorganization" package.
	DzoInverseTable = "dzo_organizations"
	// DzoColumn is the table column denoting the dzo relation/edge.
	DzoColumn = "dzo_id"
	// GeneralPositionTable is the table that holds the general_position relation/edge.
	GeneralPositionTable = "dzo_position_titles"
	// GeneralPositionInverseTable is the table name for the GeneralPosition entity.
	// It exists in this package in order to avoid circular dependency with the "generalposition" package.
	GeneralPositionInverseTable = "general_positions"
	// GeneralPositionColumn is the table column denoting the general_position relation/edge.
	GeneralPositionColumn = "general_position_id"
	// EmployeesTable is the table that holds the employees relation/edge.
	EmployeesTable = "employees"
	// EmployeesInverseTable is the table name for the Employee entity.
	// It exists in this package in order to avoid circular dependency with the "employee" package.
	EmployeesInverseTable = "employees"
	// EmployeesColumn is the table column denoting the employees relation/edge.
	EmployeesColumn = "dzo_position_id"
)

// Columns holds all SQL columns for dzopositiontitle fields.
var Columns = []string{
	FieldID,
	FieldDzoID,
	FieldClientID,
	FieldGeneralPositionID,
	FieldLocalTitle,
	FieldIsActive,
	FieldIsDeleted,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LocalTitleValidator is a validator for the "local_title" field. It is called by the builders before save.
	LocalTitleValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultIsDeleted holds the default value on creation for the "is_deleted" field.
	DefaultIsDeleted bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the DzoPositionTitle queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDzoID orders the results by the dzo_id field.
func ByDzoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDzoID, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByGeneralPositionID orders the results by the general_position_id field.
func ByGeneralPositionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGeneralPositionID, opts...).ToFunc()
}

// ByLocalTitle orders the results by the local_title field.
func ByLocalTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalTitle, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByIsDeleted orders the results by the is_deleted field.
func ByIsDeleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDeleted, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDzoField orders the results by dzo field.
func ByDzoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDzoStep(), sql.OrderByField(field, opts...))
	}
}

// ByGeneralPositionField orders the results by general_position field.
func ByGeneralPositionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGeneralPositionStep(), sql.OrderByField(field, opts...))
	}
}

// ByEmployeesCount orders the results by employees count.
func ByEmployeesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEmployeesStep(), opts...)
	}
}

// ByEmployees orders the results by employees terms.
func ByEmployees(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEmployeesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDzoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DzoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DzoTable, DzoColumn),
	)
}
func newGeneralPositionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GeneralPositionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GeneralPositionTable, GeneralPositionColumn),
	)
}
func newEmployeesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EmployeesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EmployeesTable, EmployeesColumn),
	)
}
