// Code generated by ent, DO NOT EDIT.

package supplier

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the supplier type in the database.
	Label = "supplier"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldBinOrIin holds the string denoting the bin_or_iin field in the database.
	FieldBinOrIin = "bin_or_iin"
	// FieldLocalContentPct holds the string denoting the local_content_pct field in the database.
	FieldLocalContentPct = "local_content_pct"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// Table holds the table name of the supplier in the database.
	Table = "suppliers"
)

// Columns holds all SQL columns for supplier fields.
var Columns = []string{
	FieldID,
	FieldClientID,
	FieldType,
	FieldName,
	FieldBinOrIin,
	FieldLocalContentPct,
	FieldIsActive,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// BinOrIinValidator is a validator for the "bin_or_iin" field. It is called by the builders before save.
	BinOrIinValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Type defines the type for the "type" enum field.
type Type string

// Type values.
const (
	TypeLEGAL      Type = "LEGAL"
	TypeINDIVIDUAL Type = "INDIVIDUAL"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeLEGAL, TypeINDIVIDUAL:
		return nil
	default:
		return fmt.Errorf("supplier: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Supplier queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByBinOrIin orders the results by the bin_or_iin field.
func ByBinOrIin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBinOrIin, opts...).ToFunc()
}

// ByLocalContentPct orders the results by the local_content_pct field.
func ByLocalContentPct(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalContentPct, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}
