// Code generated by ent, DO NOT EDIT.

package externaltrainingevent

import (
	"time"

	"encore.app/db/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldName, v))
}

// Format applies equality check predicate on the "format" field. It's identical to FormatEQ.
func Format(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldFormat, v))
}

// Capacity applies equality check predicate on the "capacity" field. It's identical to CapacityEQ.
func Capacity(v int) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldCapacity, v))
}

// SupplierCostVat applies equality check predicate on the "supplier_cost_vat" field. It's identical to SupplierCostVatEQ.
func SupplierCostVat(v float64) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldSupplierCostVat, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldStartDate, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CategoryID applies equality check predicate on the "category_id" field. It's identical to CategoryIDEQ.
func CategoryID(v uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldCategoryID, v))
}

// SupplierID applies equality check predicate on the "supplier_id" field. It's identical to SupplierIDEQ.
func SupplierID(v uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldSupplierID, v))
}

// ContractID applies equality check predicate on the "contract_id" field. It's identical to ContractIDEQ.
func ContractID(v uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldContractID, v))
}

// ResponsibleUserID applies equality check predicate on the "responsible_user_id" field. It's identical to ResponsibleUserIDEQ.
func ResponsibleUserID(v uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldResponsibleUserID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldContainsFold(FieldName, v))
}

// FormatEQ applies the EQ predicate on the "format" field.
func FormatEQ(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldFormat, v))
}

// FormatNEQ applies the NEQ predicate on the "format" field.
func FormatNEQ(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNEQ(FieldFormat, v))
}

// FormatIn applies the In predicate on the "format" field.
func FormatIn(vs ...string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIn(FieldFormat, vs...))
}

// FormatNotIn applies the NotIn predicate on the "format" field.
func FormatNotIn(vs ...string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotIn(FieldFormat, vs...))
}

// FormatGT applies the GT predicate on the "format" field.
func FormatGT(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldGT(FieldFormat, v))
}

// FormatGTE applies the GTE predicate on the "format" field.
func FormatGTE(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldGTE(FieldFormat, v))
}

// FormatLT applies the LT predicate on the "format" field.
func FormatLT(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldLT(FieldFormat, v))
}

// FormatLTE applies the LTE predicate on the "format" field.
func FormatLTE(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldLTE(FieldFormat, v))
}

// FormatContains applies the Contains predicate on the "format" field.
func FormatContains(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldContains(FieldFormat, v))
}

// FormatHasPrefix applies the HasPrefix predicate on the "format" field.
func FormatHasPrefix(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldHasPrefix(FieldFormat, v))
}

// FormatHasSuffix applies the HasSuffix predicate on the "format" field.
func FormatHasSuffix(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldHasSuffix(FieldFormat, v))
}

// FormatIsNil applies the IsNil predicate on the "format" field.
func FormatIsNil() predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIsNull(FieldFormat))
}

// FormatNotNil applies the NotNil predicate on the "format" field.
func FormatNotNil() predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotNull(FieldFormat))
}

// FormatEqualFold applies the EqualFold predicate on the "format" field.
func FormatEqualFold(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEqualFold(FieldFormat, v))
}

// FormatContainsFold applies the ContainsFold predicate on the "format" field.
func FormatContainsFold(v string) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldContainsFold(FieldFormat, v))
}

// CapacityEQ applies the EQ predicate on the "capacity" field.
func CapacityEQ(v int) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldCapacity, v))
}

// CapacityNEQ applies the NEQ predicate on the "capacity" field.
func CapacityNEQ(v int) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNEQ(FieldCapacity, v))
}

// CapacityIn applies the In predicate on the "capacity" field.
func CapacityIn(vs ...int) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIn(FieldCapacity, vs...))
}

// CapacityNotIn applies the NotIn predicate on the "capacity" field.
func CapacityNotIn(vs ...int) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotIn(FieldCapacity, vs...))
}

// CapacityGT applies the GT predicate on the "capacity" field.
func CapacityGT(v int) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldGT(FieldCapacity, v))
}

// CapacityGTE applies the GTE predicate on the "capacity" field.
func CapacityGTE(v int) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldGTE(FieldCapacity, v))
}

// CapacityLT applies the LT predicate on the "capacity" field.
func CapacityLT(v int) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldLT(FieldCapacity, v))
}

// CapacityLTE applies the LTE predicate on the "capacity" field.
func CapacityLTE(v int) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldLTE(FieldCapacity, v))
}

// CapacityIsNil applies the IsNil predicate on the "capacity" field.
func CapacityIsNil() predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIsNull(FieldCapacity))
}

// CapacityNotNil applies the NotNil predicate on the "capacity" field.
func CapacityNotNil() predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotNull(FieldCapacity))
}

// SupplierCostVatEQ applies the EQ predicate on the "supplier_cost_vat" field.
func SupplierCostVatEQ(v float64) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldSupplierCostVat, v))
}

// SupplierCostVatNEQ applies the NEQ predicate on the "supplier_cost_vat" field.
func SupplierCostVatNEQ(v float64) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNEQ(FieldSupplierCostVat, v))
}

// SupplierCostVatIn applies the In predicate on the "supplier_cost_vat" field.
func SupplierCostVatIn(vs ...float64) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIn(FieldSupplierCostVat, vs...))
}

// SupplierCostVatNotIn applies the NotIn predicate on the "supplier_cost_vat" field.
func SupplierCostVatNotIn(vs ...float64) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotIn(FieldSupplierCostVat, vs...))
}

// SupplierCostVatGT applies the GT predicate on the "supplier_cost_vat" field.
func SupplierCostVatGT(v float64) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldGT(FieldSupplierCostVat, v))
}

// SupplierCostVatGTE applies the GTE predicate on the "supplier_cost_vat" field.
func SupplierCostVatGTE(v float64) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldGTE(FieldSupplierCostVat, v))
}

// SupplierCostVatLT applies the LT predicate on the "supplier_cost_vat" field.
func SupplierCostVatLT(v float64) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldLT(FieldSupplierCostVat, v))
}

// SupplierCostVatLTE applies the LTE predicate on the "supplier_cost_vat" field.
func SupplierCostVatLTE(v float64) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldLTE(FieldSupplierCostVat, v))
}

// SupplierCostVatIsNil applies the IsNil predicate on the "supplier_cost_vat" field.
func SupplierCostVatIsNil() predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIsNull(FieldSupplierCostVat))
}

// SupplierCostVatNotNil applies the NotNil predicate on the "supplier_cost_vat" field.
func SupplierCostVatNotNil() predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotNull(FieldSupplierCostVat))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldLTE(FieldStartDate, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// CategoryIDEQ applies the EQ predicate on the "category_id" field.
func CategoryIDEQ(v uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldCategoryID, v))
}

// CategoryIDNEQ applies the NEQ predicate on the "category_id" field.
func CategoryIDNEQ(v uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNEQ(FieldCategoryID, v))
}

// CategoryIDIn applies the In predicate on the "category_id" field.
func CategoryIDIn(vs ...uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIn(FieldCategoryID, vs...))
}

// CategoryIDNotIn applies the NotIn predicate on the "category_id" field.
func CategoryIDNotIn(vs ...uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotIn(FieldCategoryID, vs...))
}

// CategoryIDIsNil applies the IsNil predicate on the "category_id" field.
func CategoryIDIsNil() predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIsNull(FieldCategoryID))
}

// CategoryIDNotNil applies the NotNil predicate on the "category_id" field.
func CategoryIDNotNil() predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotNull(FieldCategoryID))
}

// SupplierIDEQ applies the EQ predicate on the "supplier_id" field.
func SupplierIDEQ(v uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldSupplierID, v))
}

// SupplierIDNEQ applies the NEQ predicate on the "supplier_id" field.
func SupplierIDNEQ(v uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNEQ(FieldSupplierID, v))
}

// SupplierIDIn applies the In predicate on the "supplier_id" field.
func SupplierIDIn(vs ...uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIn(FieldSupplierID, vs...))
}

// SupplierIDNotIn applies the NotIn predicate on the "supplier_id" field.
func SupplierIDNotIn(vs ...uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotIn(FieldSupplierID, vs...))
}

// ContractIDEQ applies the EQ predicate on the "contract_id" field.
func ContractIDEQ(v uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldContractID, v))
}

// ContractIDNEQ applies the NEQ predicate on the "contract_id" field.
func ContractIDNEQ(v uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNEQ(FieldContractID, v))
}

// ContractIDIn applies the In predicate on the "contract_id" field.
func ContractIDIn(vs ...uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIn(FieldContractID, vs...))
}

// ContractIDNotIn applies the NotIn predicate on the "contract_id" field.
func ContractIDNotIn(vs ...uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotIn(FieldContractID, vs...))
}

// ResponsibleUserIDEQ applies the EQ predicate on the "responsible_user_id" field.
func ResponsibleUserIDEQ(v uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldEQ(FieldResponsibleUserID, v))
}

// ResponsibleUserIDNEQ applies the NEQ predicate on the "responsible_user_id" field.
func ResponsibleUserIDNEQ(v uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNEQ(FieldResponsibleUserID, v))
}

// ResponsibleUserIDIn applies the In predicate on the "responsible_user_id" field.
func ResponsibleUserIDIn(vs ...uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIn(FieldResponsibleUserID, vs...))
}

// ResponsibleUserIDNotIn applies the NotIn predicate on the "responsible_user_id" field.
func ResponsibleUserIDNotIn(vs ...uuid.UUID) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotIn(FieldResponsibleUserID, vs...))
}

// ResponsibleUserIDIsNil applies the IsNil predicate on the "responsible_user_id" field.
func ResponsibleUserIDIsNil() predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldIsNull(FieldResponsibleUserID))
}

// ResponsibleUserIDNotNil applies the NotNil predicate on the "responsible_user_id" field.
func ResponsibleUserIDNotNil() predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.FieldNotNull(FieldResponsibleUserID))
}

// HasCategory applies the HasEdge predicate on the "category" edge.
func HasCategory() predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCategoryWith applies the HasEdge predicate on the "category" edge with a given conditions (other predicates).
func HasCategoryWith(preds ...predicate.Category) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(func(s *sql.Selector) {
		step := newCategoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSupplier applies the HasEdge predicate on the "supplier" edge.
func HasSupplier() predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SupplierTable, SupplierColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSupplierWith applies the HasEdge predicate on the "supplier" edge with a given conditions (other predicates).
func HasSupplierWith(preds ...predicate.Supplier) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(func(s *sql.Selector) {
		step := newSupplierStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasContract applies the HasEdge predicate on the "contract" edge.
func HasContract() predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ContractTable, ContractColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContractWith applies the HasEdge predicate on the "contract" edge with a given conditions (other predicates).
func HasContractWith(preds ...predicate.ContractSupplier) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(func(s *sql.Selector) {
		step := newContractStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasResponsibleUser applies the HasEdge predicate on the "responsible_user" edge.
func HasResponsibleUser() predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ResponsibleUserTable, ResponsibleUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResponsibleUserWith applies the HasEdge predicate on the "responsible_user" edge with a given conditions (other predicates).
func HasResponsibleUserWith(preds ...predicate.User) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(func(s *sql.Selector) {
		step := newResponsibleUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExternalTrainingEvent) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExternalTrainingEvent) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExternalTrainingEvent) predicate.ExternalTrainingEvent {
	return predicate.ExternalTrainingEvent(sql.NotPredicates(p))
}
