// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"encore.app/orgstructure/contracts_dzo/ent/contractdzo"
	"encore.app/orgstructure/contracts_dzo/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContractDZODelete is the builder for deleting a ContractDZO entity.
type ContractDZODelete struct {
	config
	hooks    []Hook
	mutation *ContractDZOMutation
}

// Where appends a list predicates to the ContractDZODelete builder.
func (_d *ContractDZODelete) Where(ps ...predicate.ContractDZO) *ContractDZODelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ContractDZODelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ContractDZODelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ContractDZODelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(contractdzo.Table, sqlgraph.NewFieldSpec(contractdzo.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ContractDZODeleteOne is the builder for deleting a single ContractDZO entity.
type ContractDZODeleteOne struct {
	_d *ContractDZODelete
}

// Where appends a list predicates to the ContractDZODelete builder.
func (_d *ContractDZODeleteOne) Where(ps ...predicate.ContractDZO) *ContractDZODeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ContractDZODeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{contractdzo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ContractDZODeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
