// Code generated by ent, DO NOT EDIT.

package employee

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the employee type in the database.
	Label = "employee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// EdgeEventParticipations holds the string denoting the event_participations edge name in mutations.
	EdgeEventParticipations = "event_participations"
	// Table holds the table name of the employee in the database.
	Table = "employees"
	// EventParticipationsTable is the table that holds the event_participations relation/edge.
	EventParticipationsTable = "event_participants"
	// EventParticipationsInverseTable is the table name for the EventParticipant entity.
	// It exists in this package in order to avoid circular dependency with the "eventparticipant" package.
	EventParticipationsInverseTable = "event_participants"
	// EventParticipationsColumn is the table column denoting the event_participations relation/edge.
	EventParticipationsColumn = "employee_id"
)

// Columns holds all SQL columns for employee fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Employee queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventParticipationsCount orders the results by event_participations count.
func ByEventParticipationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventParticipationsStep(), opts...)
	}
}

// ByEventParticipations orders the results by event_participations terms.
func ByEventParticipations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventParticipationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newEventParticipationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventParticipationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventParticipationsTable, EventParticipationsColumn),
	)
}
