// Code generated by ent, DO NOT EDIT.

package contractsupplierhistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the contractsupplierhistory type in the database.
	Label = "contract_supplier_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldHistoryID holds the string denoting the history_id field in the database.
	FieldHistoryID = "history_id"
	// FieldContractID holds the string denoting the contract_id field in the database.
	FieldContractID = "contract_id"
	// FieldOperationType holds the string denoting the operation_type field in the database.
	FieldOperationType = "operation_type"
	// FieldChangedAt holds the string denoting the changed_at field in the database.
	FieldChangedAt = "changed_at"
	// FieldChangedBy holds the string denoting the changed_by field in the database.
	FieldChangedBy = "changed_by"
	// FieldSnapshot holds the string denoting the snapshot field in the database.
	FieldSnapshot = "snapshot"
	// FieldDiff holds the string denoting the diff field in the database.
	FieldDiff = "diff"
	// Table holds the table name of the contractsupplierhistory in the database.
	Table = "contract_supplier_histories"
)

// Columns holds all SQL columns for contractsupplierhistory fields.
var Columns = []string{
	FieldID,
	FieldHistoryID,
	FieldContractID,
	FieldOperationType,
	FieldChangedAt,
	FieldChangedBy,
	FieldSnapshot,
	FieldDiff,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultHistoryID holds the default value on creation for the "history_id" field.
	DefaultHistoryID func() uuid.UUID
	// OperationTypeValidator is a validator for the "operation_type" field. It is called by the builders before save.
	OperationTypeValidator func(string) error
	// DefaultChangedAt holds the default value on creation for the "changed_at" field.
	DefaultChangedAt func() time.Time
)

// OrderOption defines the ordering options for the ContractSupplierHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByHistoryID orders the results by the history_id field.
func ByHistoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHistoryID, opts...).ToFunc()
}

// ByContractID orders the results by the contract_id field.
func ByContractID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContractID, opts...).ToFunc()
}

// ByOperationType orders the results by the operation_type field.
func ByOperationType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperationType, opts...).ToFunc()
}

// ByChangedAt orders the results by the changed_at field.
func ByChangedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangedAt, opts...).ToFunc()
}

// ByChangedBy orders the results by the changed_by field.
func ByChangedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangedBy, opts...).ToFunc()
}
