// Code generated by ent, DO NOT EDIT.

package contractsupplierhistory

import (
	"time"

	"encore.app/db/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldLTE(FieldID, id))
}

// HistoryID applies equality check predicate on the "history_id" field. It's identical to HistoryIDEQ.
func HistoryID(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldEQ(FieldHistoryID, v))
}

// ContractID applies equality check predicate on the "contract_id" field. It's identical to ContractIDEQ.
func ContractID(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldEQ(FieldContractID, v))
}

// OperationType applies equality check predicate on the "operation_type" field. It's identical to OperationTypeEQ.
func OperationType(v string) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldEQ(FieldOperationType, v))
}

// ChangedAt applies equality check predicate on the "changed_at" field. It's identical to ChangedAtEQ.
func ChangedAt(v time.Time) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldEQ(FieldChangedAt, v))
}

// ChangedBy applies equality check predicate on the "changed_by" field. It's identical to ChangedByEQ.
func ChangedBy(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldEQ(FieldChangedBy, v))
}

// HistoryIDEQ applies the EQ predicate on the "history_id" field.
func HistoryIDEQ(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldEQ(FieldHistoryID, v))
}

// HistoryIDNEQ applies the NEQ predicate on the "history_id" field.
func HistoryIDNEQ(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldNEQ(FieldHistoryID, v))
}

// HistoryIDIn applies the In predicate on the "history_id" field.
func HistoryIDIn(vs ...uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldIn(FieldHistoryID, vs...))
}

// HistoryIDNotIn applies the NotIn predicate on the "history_id" field.
func HistoryIDNotIn(vs ...uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldNotIn(FieldHistoryID, vs...))
}

// HistoryIDGT applies the GT predicate on the "history_id" field.
func HistoryIDGT(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldGT(FieldHistoryID, v))
}

// HistoryIDGTE applies the GTE predicate on the "history_id" field.
func HistoryIDGTE(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldGTE(FieldHistoryID, v))
}

// HistoryIDLT applies the LT predicate on the "history_id" field.
func HistoryIDLT(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldLT(FieldHistoryID, v))
}

// HistoryIDLTE applies the LTE predicate on the "history_id" field.
func HistoryIDLTE(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldLTE(FieldHistoryID, v))
}

// ContractIDEQ applies the EQ predicate on the "contract_id" field.
func ContractIDEQ(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldEQ(FieldContractID, v))
}

// ContractIDNEQ applies the NEQ predicate on the "contract_id" field.
func ContractIDNEQ(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldNEQ(FieldContractID, v))
}

// ContractIDIn applies the In predicate on the "contract_id" field.
func ContractIDIn(vs ...uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldIn(FieldContractID, vs...))
}

// ContractIDNotIn applies the NotIn predicate on the "contract_id" field.
func ContractIDNotIn(vs ...uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldNotIn(FieldContractID, vs...))
}

// ContractIDGT applies the GT predicate on the "contract_id" field.
func ContractIDGT(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldGT(FieldContractID, v))
}

// ContractIDGTE applies the GTE predicate on the "contract_id" field.
func ContractIDGTE(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldGTE(FieldContractID, v))
}

// ContractIDLT applies the LT predicate on the "contract_id" field.
func ContractIDLT(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldLT(FieldContractID, v))
}

// ContractIDLTE applies the LTE predicate on the "contract_id" field.
func ContractIDLTE(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldLTE(FieldContractID, v))
}

// OperationTypeEQ applies the EQ predicate on the "operation_type" field.
func OperationTypeEQ(v string) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldEQ(FieldOperationType, v))
}

// OperationTypeNEQ applies the NEQ predicate on the "operation_type" field.
func OperationTypeNEQ(v string) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldNEQ(FieldOperationType, v))
}

// OperationTypeIn applies the In predicate on the "operation_type" field.
func OperationTypeIn(vs ...string) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldIn(FieldOperationType, vs...))
}

// OperationTypeNotIn applies the NotIn predicate on the "operation_type" field.
func OperationTypeNotIn(vs ...string) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldNotIn(FieldOperationType, vs...))
}

// OperationTypeGT applies the GT predicate on the "operation_type" field.
func OperationTypeGT(v string) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldGT(FieldOperationType, v))
}

// OperationTypeGTE applies the GTE predicate on the "operation_type" field.
func OperationTypeGTE(v string) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldGTE(FieldOperationType, v))
}

// OperationTypeLT applies the LT predicate on the "operation_type" field.
func OperationTypeLT(v string) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldLT(FieldOperationType, v))
}

// OperationTypeLTE applies the LTE predicate on the "operation_type" field.
func OperationTypeLTE(v string) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldLTE(FieldOperationType, v))
}

// OperationTypeContains applies the Contains predicate on the "operation_type" field.
func OperationTypeContains(v string) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldContains(FieldOperationType, v))
}

// OperationTypeHasPrefix applies the HasPrefix predicate on the "operation_type" field.
func OperationTypeHasPrefix(v string) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldHasPrefix(FieldOperationType, v))
}

// OperationTypeHasSuffix applies the HasSuffix predicate on the "operation_type" field.
func OperationTypeHasSuffix(v string) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldHasSuffix(FieldOperationType, v))
}

// OperationTypeEqualFold applies the EqualFold predicate on the "operation_type" field.
func OperationTypeEqualFold(v string) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldEqualFold(FieldOperationType, v))
}

// OperationTypeContainsFold applies the ContainsFold predicate on the "operation_type" field.
func OperationTypeContainsFold(v string) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldContainsFold(FieldOperationType, v))
}

// ChangedAtEQ applies the EQ predicate on the "changed_at" field.
func ChangedAtEQ(v time.Time) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldEQ(FieldChangedAt, v))
}

// ChangedAtNEQ applies the NEQ predicate on the "changed_at" field.
func ChangedAtNEQ(v time.Time) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldNEQ(FieldChangedAt, v))
}

// ChangedAtIn applies the In predicate on the "changed_at" field.
func ChangedAtIn(vs ...time.Time) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldIn(FieldChangedAt, vs...))
}

// ChangedAtNotIn applies the NotIn predicate on the "changed_at" field.
func ChangedAtNotIn(vs ...time.Time) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldNotIn(FieldChangedAt, vs...))
}

// ChangedAtGT applies the GT predicate on the "changed_at" field.
func ChangedAtGT(v time.Time) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldGT(FieldChangedAt, v))
}

// ChangedAtGTE applies the GTE predicate on the "changed_at" field.
func ChangedAtGTE(v time.Time) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldGTE(FieldChangedAt, v))
}

// ChangedAtLT applies the LT predicate on the "changed_at" field.
func ChangedAtLT(v time.Time) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldLT(FieldChangedAt, v))
}

// ChangedAtLTE applies the LTE predicate on the "changed_at" field.
func ChangedAtLTE(v time.Time) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldLTE(FieldChangedAt, v))
}

// ChangedByEQ applies the EQ predicate on the "changed_by" field.
func ChangedByEQ(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldEQ(FieldChangedBy, v))
}

// ChangedByNEQ applies the NEQ predicate on the "changed_by" field.
func ChangedByNEQ(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldNEQ(FieldChangedBy, v))
}

// ChangedByIn applies the In predicate on the "changed_by" field.
func ChangedByIn(vs ...uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldIn(FieldChangedBy, vs...))
}

// ChangedByNotIn applies the NotIn predicate on the "changed_by" field.
func ChangedByNotIn(vs ...uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldNotIn(FieldChangedBy, vs...))
}

// ChangedByGT applies the GT predicate on the "changed_by" field.
func ChangedByGT(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldGT(FieldChangedBy, v))
}

// ChangedByGTE applies the GTE predicate on the "changed_by" field.
func ChangedByGTE(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldGTE(FieldChangedBy, v))
}

// ChangedByLT applies the LT predicate on the "changed_by" field.
func ChangedByLT(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldLT(FieldChangedBy, v))
}

// ChangedByLTE applies the LTE predicate on the "changed_by" field.
func ChangedByLTE(v uuid.UUID) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldLTE(FieldChangedBy, v))
}

// ChangedByIsNil applies the IsNil predicate on the "changed_by" field.
func ChangedByIsNil() predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldIsNull(FieldChangedBy))
}

// ChangedByNotNil applies the NotNil predicate on the "changed_by" field.
func ChangedByNotNil() predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldNotNull(FieldChangedBy))
}

// SnapshotIsNil applies the IsNil predicate on the "snapshot" field.
func SnapshotIsNil() predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldIsNull(FieldSnapshot))
}

// SnapshotNotNil applies the NotNil predicate on the "snapshot" field.
func SnapshotNotNil() predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldNotNull(FieldSnapshot))
}

// DiffIsNil applies the IsNil predicate on the "diff" field.
func DiffIsNil() predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldIsNull(FieldDiff))
}

// DiffNotNil applies the NotNil predicate on the "diff" field.
func DiffNotNil() predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.FieldNotNull(FieldDiff))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ContractSupplierHistory) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ContractSupplierHistory) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ContractSupplierHistory) predicate.ContractSupplierHistory {
	return predicate.ContractSupplierHistory(sql.NotPredicates(p))
}
