// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CertificatesColumns holds the columns for the "certificates" table.
	CertificatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "employee_id", Type: field.TypeInt64},
		{Name: "dzo_id", Type: field.TypeInt64, Nullable: true},
		{Name: "title", Type: field.TypeString, Size: 255},
		{Name: "file_url", Type: field.TypeString},
		{Name: "issue_date", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "expiration_date", Type: field.TypeTime, Nullable: true, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// CertificatesTable holds the schema information for the "certificates" table.
	CertificatesTable = &schema.Table{
		Name:       "certificates",
		Columns:    CertificatesColumns,
		PrimaryKey: []*schema.Column{CertificatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "certificate_employee_id",
				Unique:  false,
				Columns: []*schema.Column{CertificatesColumns[1]},
			},
			{
				Name:    "certificate_dzo_id",
				Unique:  false,
				Columns: []*schema.Column{CertificatesColumns[2]},
			},
			{
				Name:    "certificate_is_active",
				Unique:  false,
				Columns: []*schema.Column{CertificatesColumns[7]},
			},
		},
	}
	// OrganizationsColumns holds the columns for the "organizations" table.
	OrganizationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "type", Type: field.TypeString, Size: 50, Default: "subsidiary"},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "parent_id", Type: field.TypeUUID, Nullable: true},
	}
	// OrganizationsTable holds the schema information for the "organizations" table.
	OrganizationsTable = &schema.Table{
		Name:       "organizations",
		Columns:    OrganizationsColumns,
		PrimaryKey: []*schema.Column{OrganizationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "organizations_organizations_children",
				Columns:    []*schema.Column{OrganizationsColumns[7]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "organization_parent_id",
				Unique:  false,
				Columns: []*schema.Column{OrganizationsColumns[7]},
			},
			{
				Name:    "organization_code",
				Unique:  false,
				Columns: []*schema.Column{OrganizationsColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "keycloak_user_id", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "email", Type: field.TypeString, Size: 255},
		{Name: "role", Type: field.TypeString, Size: 20, Default: "EMP"},
		{Name: "dzo_id", Type: field.TypeUUID, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "is_onboarded", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[2]},
			},
			{
				Name:    "user_dzo_id",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CertificatesTable,
		OrganizationsTable,
		UsersTable,
	}
)

func init() {
	OrganizationsTable.ForeignKeys[0].RefTable = OrganizationsTable
}
