// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ClientsColumns holds the columns for the "clients" table.
	ClientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "domain", Type: field.TypeString, Nullable: true, Size: 100},
		{Name: "language", Type: field.TypeString, Nullable: true, Size: 10},
		{Name: "user_limit", Type: field.TypeInt, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
	}
	// ClientsTable holds the schema information for the "clients" table.
	ClientsTable = &schema.Table{
		Name:       "clients",
		Columns:    ClientsColumns,
		PrimaryKey: []*schema.Column{ClientsColumns[0]},
	}
	// OrganizationsColumns holds the columns for the "organizations" table.
	OrganizationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString, Size: 255},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 100},
		{Name: "type", Type: field.TypeString, Size: 50, Default: "subsidiary"},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "parent_id", Type: field.TypeUUID, Nullable: true},
	}
	// OrganizationsTable holds the schema information for the "organizations" table.
	OrganizationsTable = &schema.Table{
		Name:       "organizations",
		Columns:    OrganizationsColumns,
		PrimaryKey: []*schema.Column{OrganizationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "organizations_organizations_children",
				Columns:    []*schema.Column{OrganizationsColumns[7]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "organization_parent_id",
				Unique:  false,
				Columns: []*schema.Column{OrganizationsColumns[7]},
			},
			{
				Name:    "organization_code",
				Unique:  false,
				Columns: []*schema.Column{OrganizationsColumns[2]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "keycloak_user_id", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "email", Type: field.TypeString, Size: 255},
		{Name: "role", Type: field.TypeString, Size: 20, Default: "EMP"},
		{Name: "dzo_id", Type: field.TypeUUID, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "is_onboarded", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "updated_at", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "timestamptz"}},
		{Name: "client_id", Type: field.TypeUUID, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_clients_users",
				Columns:    []*schema.Column{UsersColumns[9]},
				RefColumns: []*schema.Column{ClientsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[2]},
			},
			{
				Name:    "user_dzo_id",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ClientsTable,
		OrganizationsTable,
		UsersTable,
	}
)

func init() {
	ClientsTable.Annotation = &entsql.Annotation{
		Table: "clients",
	}
	OrganizationsTable.ForeignKeys[0].RefTable = OrganizationsTable
	UsersTable.ForeignKeys[0].RefTable = ClientsTable
}
