// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// DzoOrganization is the predicate function for dzoorganization builders.
type DzoOrganization func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// EventParticipant is the predicate function for eventparticipant builders.
type EventParticipant func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
