// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"encore.app/db/ent/certificate"
	"encore.app/db/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CertificateUpdate is the builder for updating Certificate entities.
type CertificateUpdate struct {
	config
	hooks    []Hook
	mutation *CertificateMutation
}

// Where appends a list predicates to the CertificateUpdate builder.
func (_u *CertificateUpdate) Where(ps ...predicate.Certificate) *CertificateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmployeeID sets the "employee_id" field.
func (_u *CertificateUpdate) SetEmployeeID(v uuid.UUID) *CertificateUpdate {
	_u.mutation.SetEmployeeID(v)
	return _u
}

// SetNillableEmployeeID sets the "employee_id" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableEmployeeID(v *uuid.UUID) *CertificateUpdate {
	if v != nil {
		_u.SetEmployeeID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *CertificateUpdate) SetType(v certificate.Type) *CertificateUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableType(v *certificate.Type) *CertificateUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *CertificateUpdate) SetTitle(v string) *CertificateUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableTitle(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetIssuedDate sets the "issued_date" field.
func (_u *CertificateUpdate) SetIssuedDate(v time.Time) *CertificateUpdate {
	_u.mutation.SetIssuedDate(v)
	return _u
}

// SetNillableIssuedDate sets the "issued_date" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableIssuedDate(v *time.Time) *CertificateUpdate {
	if v != nil {
		_u.SetIssuedDate(*v)
	}
	return _u
}

// SetExpiryDate sets the "expiry_date" field.
func (_u *CertificateUpdate) SetExpiryDate(v time.Time) *CertificateUpdate {
	_u.mutation.SetExpiryDate(v)
	return _u
}

// SetNillableExpiryDate sets the "expiry_date" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableExpiryDate(v *time.Time) *CertificateUpdate {
	if v != nil {
		_u.SetExpiryDate(*v)
	}
	return _u
}

// ClearExpiryDate clears the value of the "expiry_date" field.
func (_u *CertificateUpdate) ClearExpiryDate() *CertificateUpdate {
	_u.mutation.ClearExpiryDate()
	return _u
}

// SetFileURL sets the "file_url" field.
func (_u *CertificateUpdate) SetFileURL(v string) *CertificateUpdate {
	_u.mutation.SetFileURL(v)
	return _u
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableFileURL(v *string) *CertificateUpdate {
	if v != nil {
		_u.SetFileURL(*v)
	}
	return _u
}

// ClearFileURL clears the value of the "file_url" field.
func (_u *CertificateUpdate) ClearFileURL() *CertificateUpdate {
	_u.mutation.ClearFileURL()
	return _u
}

// SetUploadedBy sets the "uploaded_by" field.
func (_u *CertificateUpdate) SetUploadedBy(v uuid.UUID) *CertificateUpdate {
	_u.mutation.SetUploadedBy(v)
	return _u
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableUploadedBy(v *uuid.UUID) *CertificateUpdate {
	if v != nil {
		_u.SetUploadedBy(*v)
	}
	return _u
}

// ClearUploadedBy clears the value of the "uploaded_by" field.
func (_u *CertificateUpdate) ClearUploadedBy() *CertificateUpdate {
	_u.mutation.ClearUploadedBy()
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *CertificateUpdate) SetEntityType(v certificate.EntityType) *CertificateUpdate {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableEntityType(v *certificate.EntityType) *CertificateUpdate {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *CertificateUpdate) SetEntityID(v uuid.UUID) *CertificateUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableEntityID(v *uuid.UUID) *CertificateUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *CertificateUpdate) SetIsActive(v bool) *CertificateUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *CertificateUpdate) SetNillableIsActive(v *bool) *CertificateUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CertificateUpdate) SetUpdatedAt(v time.Time) *CertificateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CertificateMutation object of the builder.
func (_u *CertificateUpdate) Mutation() *CertificateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CertificateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CertificateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CertificateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CertificateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CertificateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := certificate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CertificateUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := certificate.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Certificate.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := certificate.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Certificate.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityType(); ok {
		if err := certificate.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "Certificate.entity_type": %w`, err)}
		}
	}
	return nil
}

func (_u *CertificateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(certificate.Table, certificate.Columns, sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EmployeeID(); ok {
		_spec.SetField(certificate.FieldEmployeeID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(certificate.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(certificate.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedDate(); ok {
		_spec.SetField(certificate.FieldIssuedDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiryDate(); ok {
		_spec.SetField(certificate.FieldExpiryDate, field.TypeTime, value)
	}
	if _u.mutation.ExpiryDateCleared() {
		_spec.ClearField(certificate.FieldExpiryDate, field.TypeTime)
	}
	if value, ok := _u.mutation.FileURL(); ok {
		_spec.SetField(certificate.FieldFileURL, field.TypeString, value)
	}
	if _u.mutation.FileURLCleared() {
		_spec.ClearField(certificate.FieldFileURL, field.TypeString)
	}
	if value, ok := _u.mutation.UploadedBy(); ok {
		_spec.SetField(certificate.FieldUploadedBy, field.TypeUUID, value)
	}
	if _u.mutation.UploadedByCleared() {
		_spec.ClearField(certificate.FieldUploadedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(certificate.FieldEntityType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(certificate.FieldEntityID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(certificate.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(certificate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CertificateUpdateOne is the builder for updating a single Certificate entity.
type CertificateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CertificateMutation
}

// SetEmployeeID sets the "employee_id" field.
func (_u *CertificateUpdateOne) SetEmployeeID(v uuid.UUID) *CertificateUpdateOne {
	_u.mutation.SetEmployeeID(v)
	return _u
}

// SetNillableEmployeeID sets the "employee_id" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableEmployeeID(v *uuid.UUID) *CertificateUpdateOne {
	if v != nil {
		_u.SetEmployeeID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *CertificateUpdateOne) SetType(v certificate.Type) *CertificateUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableType(v *certificate.Type) *CertificateUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *CertificateUpdateOne) SetTitle(v string) *CertificateUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableTitle(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetIssuedDate sets the "issued_date" field.
func (_u *CertificateUpdateOne) SetIssuedDate(v time.Time) *CertificateUpdateOne {
	_u.mutation.SetIssuedDate(v)
	return _u
}

// SetNillableIssuedDate sets the "issued_date" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableIssuedDate(v *time.Time) *CertificateUpdateOne {
	if v != nil {
		_u.SetIssuedDate(*v)
	}
	return _u
}

// SetExpiryDate sets the "expiry_date" field.
func (_u *CertificateUpdateOne) SetExpiryDate(v time.Time) *CertificateUpdateOne {
	_u.mutation.SetExpiryDate(v)
	return _u
}

// SetNillableExpiryDate sets the "expiry_date" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableExpiryDate(v *time.Time) *CertificateUpdateOne {
	if v != nil {
		_u.SetExpiryDate(*v)
	}
	return _u
}

// ClearExpiryDate clears the value of the "expiry_date" field.
func (_u *CertificateUpdateOne) ClearExpiryDate() *CertificateUpdateOne {
	_u.mutation.ClearExpiryDate()
	return _u
}

// SetFileURL sets the "file_url" field.
func (_u *CertificateUpdateOne) SetFileURL(v string) *CertificateUpdateOne {
	_u.mutation.SetFileURL(v)
	return _u
}

// SetNillableFileURL sets the "file_url" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableFileURL(v *string) *CertificateUpdateOne {
	if v != nil {
		_u.SetFileURL(*v)
	}
	return _u
}

// ClearFileURL clears the value of the "file_url" field.
func (_u *CertificateUpdateOne) ClearFileURL() *CertificateUpdateOne {
	_u.mutation.ClearFileURL()
	return _u
}

// SetUploadedBy sets the "uploaded_by" field.
func (_u *CertificateUpdateOne) SetUploadedBy(v uuid.UUID) *CertificateUpdateOne {
	_u.mutation.SetUploadedBy(v)
	return _u
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableUploadedBy(v *uuid.UUID) *CertificateUpdateOne {
	if v != nil {
		_u.SetUploadedBy(*v)
	}
	return _u
}

// ClearUploadedBy clears the value of the "uploaded_by" field.
func (_u *CertificateUpdateOne) ClearUploadedBy() *CertificateUpdateOne {
	_u.mutation.ClearUploadedBy()
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *CertificateUpdateOne) SetEntityType(v certificate.EntityType) *CertificateUpdateOne {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableEntityType(v *certificate.EntityType) *CertificateUpdateOne {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *CertificateUpdateOne) SetEntityID(v uuid.UUID) *CertificateUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableEntityID(v *uuid.UUID) *CertificateUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *CertificateUpdateOne) SetIsActive(v bool) *CertificateUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *CertificateUpdateOne) SetNillableIsActive(v *bool) *CertificateUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CertificateUpdateOne) SetUpdatedAt(v time.Time) *CertificateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the CertificateMutation object of the builder.
func (_u *CertificateUpdateOne) Mutation() *CertificateMutation {
	return _u.mutation
}

// Where appends a list predicates to the CertificateUpdate builder.
func (_u *CertificateUpdateOne) Where(ps ...predicate.Certificate) *CertificateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CertificateUpdateOne) Select(field string, fields ...string) *CertificateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Certificate entity.
func (_u *CertificateUpdateOne) Save(ctx context.Context) (*Certificate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CertificateUpdateOne) SaveX(ctx context.Context) *Certificate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CertificateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CertificateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CertificateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := certificate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CertificateUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := certificate.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Certificate.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := certificate.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Certificate.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EntityType(); ok {
		if err := certificate.EntityTypeValidator(v); err != nil {
			return &ValidationError{Name: "entity_type", err: fmt.Errorf(`ent: validator failed for field "Certificate.entity_type": %w`, err)}
		}
	}
	return nil
}

func (_u *CertificateUpdateOne) sqlSave(ctx context.Context) (_node *Certificate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(certificate.Table, certificate.Columns, sqlgraph.NewFieldSpec(certificate.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Certificate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, certificate.FieldID)
		for _, f := range fields {
			if !certificate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != certificate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EmployeeID(); ok {
		_spec.SetField(certificate.FieldEmployeeID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(certificate.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(certificate.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.IssuedDate(); ok {
		_spec.SetField(certificate.FieldIssuedDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiryDate(); ok {
		_spec.SetField(certificate.FieldExpiryDate, field.TypeTime, value)
	}
	if _u.mutation.ExpiryDateCleared() {
		_spec.ClearField(certificate.FieldExpiryDate, field.TypeTime)
	}
	if value, ok := _u.mutation.FileURL(); ok {
		_spec.SetField(certificate.FieldFileURL, field.TypeString, value)
	}
	if _u.mutation.FileURLCleared() {
		_spec.ClearField(certificate.FieldFileURL, field.TypeString)
	}
	if value, ok := _u.mutation.UploadedBy(); ok {
		_spec.SetField(certificate.FieldUploadedBy, field.TypeUUID, value)
	}
	if _u.mutation.UploadedByCleared() {
		_spec.ClearField(certificate.FieldUploadedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(certificate.FieldEntityType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(certificate.FieldEntityID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(certificate.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(certificate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Certificate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{certificate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
