// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"encore.app/db/ent/clients"
	"encore.app/db/ent/event"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ClientsCreate is the builder for creating a Clients entity.
type ClientsCreate struct {
	config
	mutation *ClientsMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ClientsCreate) SetName(v string) *ClientsCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDomain sets the "domain" field.
func (_c *ClientsCreate) SetDomain(v string) *ClientsCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_c *ClientsCreate) SetNillableDomain(v *string) *ClientsCreate {
	if v != nil {
		_c.SetDomain(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *ClientsCreate) SetIsActive(v bool) *ClientsCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *ClientsCreate) SetNillableIsActive(v *bool) *ClientsCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ClientsCreate) SetCreatedAt(v time.Time) *ClientsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ClientsCreate) SetNillableCreatedAt(v *time.Time) *ClientsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ClientsCreate) SetID(v uuid.UUID) *ClientsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ClientsCreate) SetNillableID(v *uuid.UUID) *ClientsCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_c *ClientsCreate) AddEventIDs(ids ...uuid.UUID) *ClientsCreate {
	_c.mutation.AddEventIDs(ids...)
	return _c
}

// AddEvents adds the "events" edges to the Event entity.
func (_c *ClientsCreate) AddEvents(v ...*Event) *ClientsCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEventIDs(ids...)
}

// Mutation returns the ClientsMutation object of the builder.
func (_c *ClientsCreate) Mutation() *ClientsMutation {
	return _c.mutation
}

// Save creates the Clients in the database.
func (_c *ClientsCreate) Save(ctx context.Context) (*Clients, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClientsCreate) SaveX(ctx context.Context) *Clients {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ClientsCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := clients.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := clients.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := clients.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClientsCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Clients.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := clients.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Clients.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Domain(); ok {
		if err := clients.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Clients.domain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Clients.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Clients.created_at"`)}
	}
	return nil
}

func (_c *ClientsCreate) sqlSave(ctx context.Context) (*Clients, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClientsCreate) createSpec() (*Clients, *sqlgraph.CreateSpec) {
	var (
		_node = &Clients{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(clients.Table, sqlgraph.NewFieldSpec(clients.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(clients.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(clients.FieldDomain, field.TypeString, value)
		_node.Domain = &value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(clients.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(clients.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clients.EventsTable,
			Columns: []string{clients.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClientsCreateBulk is the builder for creating many Clients entities in bulk.
type ClientsCreateBulk struct {
	config
	err      error
	builders []*ClientsCreate
}

// Save creates the Clients entities in the database.
func (_c *ClientsCreateBulk) Save(ctx context.Context) ([]*Clients, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Clients, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClientsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClientsCreateBulk) SaveX(ctx context.Context) []*Clients {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
