// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"encore.app/db/ent/contractsupplierhistory"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ContractSupplierHistory is the model entity for the ContractSupplierHistory schema.
type ContractSupplierHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// HistoryID holds the value of the "history_id" field.
	HistoryID uuid.UUID `json:"history_id,omitempty"`
	// ContractID holds the value of the "contract_id" field.
	ContractID uuid.UUID `json:"contract_id,omitempty"`
	// OperationType holds the value of the "operation_type" field.
	OperationType string `json:"operation_type,omitempty"`
	// ChangedAt holds the value of the "changed_at" field.
	ChangedAt time.Time `json:"changed_at,omitempty"`
	// ChangedBy holds the value of the "changed_by" field.
	ChangedBy *uuid.UUID `json:"changed_by,omitempty"`
	// Snapshot holds the value of the "snapshot" field.
	Snapshot map[string]interface{} `json:"snapshot,omitempty"`
	// Diff holds the value of the "diff" field.
	Diff         map[string]interface{} `json:"diff,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContractSupplierHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contractsupplierhistory.FieldChangedBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case contractsupplierhistory.FieldSnapshot, contractsupplierhistory.FieldDiff:
			values[i] = new([]byte)
		case contractsupplierhistory.FieldID:
			values[i] = new(sql.NullInt64)
		case contractsupplierhistory.FieldOperationType:
			values[i] = new(sql.NullString)
		case contractsupplierhistory.FieldChangedAt:
			values[i] = new(sql.NullTime)
		case contractsupplierhistory.FieldHistoryID, contractsupplierhistory.FieldContractID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContractSupplierHistory fields.
func (_m *ContractSupplierHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contractsupplierhistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case contractsupplierhistory.FieldHistoryID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field history_id", values[i])
			} else if value != nil {
				_m.HistoryID = *value
			}
		case contractsupplierhistory.FieldContractID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field contract_id", values[i])
			} else if value != nil {
				_m.ContractID = *value
			}
		case contractsupplierhistory.FieldOperationType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operation_type", values[i])
			} else if value.Valid {
				_m.OperationType = value.String
			}
		case contractsupplierhistory.FieldChangedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field changed_at", values[i])
			} else if value.Valid {
				_m.ChangedAt = value.Time
			}
		case contractsupplierhistory.FieldChangedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field changed_by", values[i])
			} else if value.Valid {
				_m.ChangedBy = new(uuid.UUID)
				*_m.ChangedBy = *value.S.(*uuid.UUID)
			}
		case contractsupplierhistory.FieldSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Snapshot); err != nil {
					return fmt.Errorf("unmarshal field snapshot: %w", err)
				}
			}
		case contractsupplierhistory.FieldDiff:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field diff", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Diff); err != nil {
					return fmt.Errorf("unmarshal field diff: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContractSupplierHistory.
// This includes values selected through modifiers, order, etc.
func (_m *ContractSupplierHistory) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ContractSupplierHistory.
// Note that you need to call ContractSupplierHistory.Unwrap() before calling this method if this ContractSupplierHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ContractSupplierHistory) Update() *ContractSupplierHistoryUpdateOne {
	return NewContractSupplierHistoryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ContractSupplierHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ContractSupplierHistory) Unwrap() *ContractSupplierHistory {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContractSupplierHistory is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ContractSupplierHistory) String() string {
	var builder strings.Builder
	builder.WriteString("ContractSupplierHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("history_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.HistoryID))
	builder.WriteString(", ")
	builder.WriteString("contract_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContractID))
	builder.WriteString(", ")
	builder.WriteString("operation_type=")
	builder.WriteString(_m.OperationType)
	builder.WriteString(", ")
	builder.WriteString("changed_at=")
	builder.WriteString(_m.ChangedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ChangedBy; v != nil {
		builder.WriteString("changed_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.Snapshot))
	builder.WriteString(", ")
	builder.WriteString("diff=")
	builder.WriteString(fmt.Sprintf("%v", _m.Diff))
	builder.WriteByte(')')
	return builder.String()
}

// ContractSupplierHistories is a parsable slice of ContractSupplierHistory.
type ContractSupplierHistories []*ContractSupplierHistory
