// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"encore.app/db/ent/contractsupplier"
	"encore.app/db/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ContractSupplierUpdate is the builder for updating ContractSupplier entities.
type ContractSupplierUpdate struct {
	config
	hooks    []Hook
	mutation *ContractSupplierMutation
}

// Where appends a list predicates to the ContractSupplierUpdate builder.
func (_u *ContractSupplierUpdate) Where(ps ...predicate.ContractSupplier) *ContractSupplierUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSupplierID sets the "supplier_id" field.
func (_u *ContractSupplierUpdate) SetSupplierID(v uuid.UUID) *ContractSupplierUpdate {
	_u.mutation.SetSupplierID(v)
	return _u
}

// SetNillableSupplierID sets the "supplier_id" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableSupplierID(v *uuid.UUID) *ContractSupplierUpdate {
	if v != nil {
		_u.SetSupplierID(*v)
	}
	return _u
}

// SetContractNumber sets the "contract_number" field.
func (_u *ContractSupplierUpdate) SetContractNumber(v string) *ContractSupplierUpdate {
	_u.mutation.SetContractNumber(v)
	return _u
}

// SetNillableContractNumber sets the "contract_number" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableContractNumber(v *string) *ContractSupplierUpdate {
	if v != nil {
		_u.SetContractNumber(*v)
	}
	return _u
}

// SetVatFlag sets the "vat_flag" field.
func (_u *ContractSupplierUpdate) SetVatFlag(v bool) *ContractSupplierUpdate {
	_u.mutation.SetVatFlag(v)
	return _u
}

// SetNillableVatFlag sets the "vat_flag" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableVatFlag(v *bool) *ContractSupplierUpdate {
	if v != nil {
		_u.SetVatFlag(*v)
	}
	return _u
}

// SetSignedDate sets the "signed_date" field.
func (_u *ContractSupplierUpdate) SetSignedDate(v time.Time) *ContractSupplierUpdate {
	_u.mutation.SetSignedDate(v)
	return _u
}

// SetNillableSignedDate sets the "signed_date" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableSignedDate(v *time.Time) *ContractSupplierUpdate {
	if v != nil {
		_u.SetSignedDate(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ContractSupplierUpdate) SetAmount(v float64) *ContractSupplierUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableAmount(v *float64) *ContractSupplierUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ContractSupplierUpdate) AddAmount(v float64) *ContractSupplierUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetAmountCurrency sets the "amount_currency" field.
func (_u *ContractSupplierUpdate) SetAmountCurrency(v float64) *ContractSupplierUpdate {
	_u.mutation.ResetAmountCurrency()
	_u.mutation.SetAmountCurrency(v)
	return _u
}

// SetNillableAmountCurrency sets the "amount_currency" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableAmountCurrency(v *float64) *ContractSupplierUpdate {
	if v != nil {
		_u.SetAmountCurrency(*v)
	}
	return _u
}

// AddAmountCurrency adds value to the "amount_currency" field.
func (_u *ContractSupplierUpdate) AddAmountCurrency(v float64) *ContractSupplierUpdate {
	_u.mutation.AddAmountCurrency(v)
	return _u
}

// ClearAmountCurrency clears the value of the "amount_currency" field.
func (_u *ContractSupplierUpdate) ClearAmountCurrency() *ContractSupplierUpdate {
	_u.mutation.ClearAmountCurrency()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ContractSupplierUpdate) SetCurrency(v string) *ContractSupplierUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableCurrency(v *string) *ContractSupplierUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// ClearCurrency clears the value of the "currency" field.
func (_u *ContractSupplierUpdate) ClearCurrency() *ContractSupplierUpdate {
	_u.mutation.ClearCurrency()
	return _u
}

// SetBalanceAtYearEnd sets the "balance_at_year_end" field.
func (_u *ContractSupplierUpdate) SetBalanceAtYearEnd(v float64) *ContractSupplierUpdate {
	_u.mutation.ResetBalanceAtYearEnd()
	_u.mutation.SetBalanceAtYearEnd(v)
	return _u
}

// SetNillableBalanceAtYearEnd sets the "balance_at_year_end" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableBalanceAtYearEnd(v *float64) *ContractSupplierUpdate {
	if v != nil {
		_u.SetBalanceAtYearEnd(*v)
	}
	return _u
}

// AddBalanceAtYearEnd adds value to the "balance_at_year_end" field.
func (_u *ContractSupplierUpdate) AddBalanceAtYearEnd(v float64) *ContractSupplierUpdate {
	_u.mutation.AddBalanceAtYearEnd(v)
	return _u
}

// ClearBalanceAtYearEnd clears the value of the "balance_at_year_end" field.
func (_u *ContractSupplierUpdate) ClearBalanceAtYearEnd() *ContractSupplierUpdate {
	_u.mutation.ClearBalanceAtYearEnd()
	return _u
}

// SetAmendmentNumber sets the "amendment_number" field.
func (_u *ContractSupplierUpdate) SetAmendmentNumber(v string) *ContractSupplierUpdate {
	_u.mutation.SetAmendmentNumber(v)
	return _u
}

// SetNillableAmendmentNumber sets the "amendment_number" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableAmendmentNumber(v *string) *ContractSupplierUpdate {
	if v != nil {
		_u.SetAmendmentNumber(*v)
	}
	return _u
}

// ClearAmendmentNumber clears the value of the "amendment_number" field.
func (_u *ContractSupplierUpdate) ClearAmendmentNumber() *ContractSupplierUpdate {
	_u.mutation.ClearAmendmentNumber()
	return _u
}

// SetAmendmentDate sets the "amendment_date" field.
func (_u *ContractSupplierUpdate) SetAmendmentDate(v time.Time) *ContractSupplierUpdate {
	_u.mutation.SetAmendmentDate(v)
	return _u
}

// SetNillableAmendmentDate sets the "amendment_date" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableAmendmentDate(v *time.Time) *ContractSupplierUpdate {
	if v != nil {
		_u.SetAmendmentDate(*v)
	}
	return _u
}

// ClearAmendmentDate clears the value of the "amendment_date" field.
func (_u *ContractSupplierUpdate) ClearAmendmentDate() *ContractSupplierUpdate {
	_u.mutation.ClearAmendmentDate()
	return _u
}

// SetAmendmentAmount sets the "amendment_amount" field.
func (_u *ContractSupplierUpdate) SetAmendmentAmount(v float64) *ContractSupplierUpdate {
	_u.mutation.ResetAmendmentAmount()
	_u.mutation.SetAmendmentAmount(v)
	return _u
}

// SetNillableAmendmentAmount sets the "amendment_amount" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableAmendmentAmount(v *float64) *ContractSupplierUpdate {
	if v != nil {
		_u.SetAmendmentAmount(*v)
	}
	return _u
}

// AddAmendmentAmount adds value to the "amendment_amount" field.
func (_u *ContractSupplierUpdate) AddAmendmentAmount(v float64) *ContractSupplierUpdate {
	_u.mutation.AddAmendmentAmount(v)
	return _u
}

// ClearAmendmentAmount clears the value of the "amendment_amount" field.
func (_u *ContractSupplierUpdate) ClearAmendmentAmount() *ContractSupplierUpdate {
	_u.mutation.ClearAmendmentAmount()
	return _u
}

// SetTotalWithAmendment sets the "total_with_amendment" field.
func (_u *ContractSupplierUpdate) SetTotalWithAmendment(v float64) *ContractSupplierUpdate {
	_u.mutation.ResetTotalWithAmendment()
	_u.mutation.SetTotalWithAmendment(v)
	return _u
}

// SetNillableTotalWithAmendment sets the "total_with_amendment" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableTotalWithAmendment(v *float64) *ContractSupplierUpdate {
	if v != nil {
		_u.SetTotalWithAmendment(*v)
	}
	return _u
}

// AddTotalWithAmendment adds value to the "total_with_amendment" field.
func (_u *ContractSupplierUpdate) AddTotalWithAmendment(v float64) *ContractSupplierUpdate {
	_u.mutation.AddTotalWithAmendment(v)
	return _u
}

// SetRemainingAmount sets the "remaining_amount" field.
func (_u *ContractSupplierUpdate) SetRemainingAmount(v float64) *ContractSupplierUpdate {
	_u.mutation.ResetRemainingAmount()
	_u.mutation.SetRemainingAmount(v)
	return _u
}

// SetNillableRemainingAmount sets the "remaining_amount" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableRemainingAmount(v *float64) *ContractSupplierUpdate {
	if v != nil {
		_u.SetRemainingAmount(*v)
	}
	return _u
}

// AddRemainingAmount adds value to the "remaining_amount" field.
func (_u *ContractSupplierUpdate) AddRemainingAmount(v float64) *ContractSupplierUpdate {
	_u.mutation.AddRemainingAmount(v)
	return _u
}

// SetFileKey sets the "file_key" field.
func (_u *ContractSupplierUpdate) SetFileKey(v string) *ContractSupplierUpdate {
	_u.mutation.SetFileKey(v)
	return _u
}

// SetNillableFileKey sets the "file_key" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableFileKey(v *string) *ContractSupplierUpdate {
	if v != nil {
		_u.SetFileKey(*v)
	}
	return _u
}

// ClearFileKey clears the value of the "file_key" field.
func (_u *ContractSupplierUpdate) ClearFileKey() *ContractSupplierUpdate {
	_u.mutation.ClearFileKey()
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *ContractSupplierUpdate) SetFileName(v string) *ContractSupplierUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableFileName(v *string) *ContractSupplierUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// ClearFileName clears the value of the "file_name" field.
func (_u *ContractSupplierUpdate) ClearFileName() *ContractSupplierUpdate {
	_u.mutation.ClearFileName()
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *ContractSupplierUpdate) SetFileSize(v int64) *ContractSupplierUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableFileSize(v *int64) *ContractSupplierUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *ContractSupplierUpdate) AddFileSize(v int64) *ContractSupplierUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// ClearFileSize clears the value of the "file_size" field.
func (_u *ContractSupplierUpdate) ClearFileSize() *ContractSupplierUpdate {
	_u.mutation.ClearFileSize()
	return _u
}

// SetFileMimeType sets the "file_mime_type" field.
func (_u *ContractSupplierUpdate) SetFileMimeType(v string) *ContractSupplierUpdate {
	_u.mutation.SetFileMimeType(v)
	return _u
}

// SetNillableFileMimeType sets the "file_mime_type" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableFileMimeType(v *string) *ContractSupplierUpdate {
	if v != nil {
		_u.SetFileMimeType(*v)
	}
	return _u
}

// ClearFileMimeType clears the value of the "file_mime_type" field.
func (_u *ContractSupplierUpdate) ClearFileMimeType() *ContractSupplierUpdate {
	_u.mutation.ClearFileMimeType()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ContractSupplierUpdate) SetIsActive(v bool) *ContractSupplierUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ContractSupplierUpdate) SetNillableIsActive(v *bool) *ContractSupplierUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ContractSupplierUpdate) SetUpdatedAt(v time.Time) *ContractSupplierUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ContractSupplierMutation object of the builder.
func (_u *ContractSupplierUpdate) Mutation() *ContractSupplierMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ContractSupplierUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContractSupplierUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ContractSupplierUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContractSupplierUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ContractSupplierUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := contractsupplier.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContractSupplierUpdate) check() error {
	if v, ok := _u.mutation.ContractNumber(); ok {
		if err := contractsupplier.ContractNumberValidator(v); err != nil {
			return &ValidationError{Name: "contract_number", err: fmt.Errorf(`ent: validator failed for field "ContractSupplier.contract_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := contractsupplier.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "ContractSupplier.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmendmentNumber(); ok {
		if err := contractsupplier.AmendmentNumberValidator(v); err != nil {
			return &ValidationError{Name: "amendment_number", err: fmt.Errorf(`ent: validator failed for field "ContractSupplier.amendment_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileKey(); ok {
		if err := contractsupplier.FileKeyValidator(v); err != nil {
			return &ValidationError{Name: "file_key", err: fmt.Errorf(`ent: validator failed for field "ContractSupplier.file_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := contractsupplier.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "ContractSupplier.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileMimeType(); ok {
		if err := contractsupplier.FileMimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "file_mime_type", err: fmt.Errorf(`ent: validator failed for field "ContractSupplier.file_mime_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ContractSupplierUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contractsupplier.Table, contractsupplier.Columns, sqlgraph.NewFieldSpec(contractsupplier.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SupplierID(); ok {
		_spec.SetField(contractsupplier.FieldSupplierID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ContractNumber(); ok {
		_spec.SetField(contractsupplier.FieldContractNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.VatFlag(); ok {
		_spec.SetField(contractsupplier.FieldVatFlag, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SignedDate(); ok {
		_spec.SetField(contractsupplier.FieldSignedDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(contractsupplier.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(contractsupplier.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AmountCurrency(); ok {
		_spec.SetField(contractsupplier.FieldAmountCurrency, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCurrency(); ok {
		_spec.AddField(contractsupplier.FieldAmountCurrency, field.TypeFloat64, value)
	}
	if _u.mutation.AmountCurrencyCleared() {
		_spec.ClearField(contractsupplier.FieldAmountCurrency, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(contractsupplier.FieldCurrency, field.TypeString, value)
	}
	if _u.mutation.CurrencyCleared() {
		_spec.ClearField(contractsupplier.FieldCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.BalanceAtYearEnd(); ok {
		_spec.SetField(contractsupplier.FieldBalanceAtYearEnd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAtYearEnd(); ok {
		_spec.AddField(contractsupplier.FieldBalanceAtYearEnd, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceAtYearEndCleared() {
		_spec.ClearField(contractsupplier.FieldBalanceAtYearEnd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AmendmentNumber(); ok {
		_spec.SetField(contractsupplier.FieldAmendmentNumber, field.TypeString, value)
	}
	if _u.mutation.AmendmentNumberCleared() {
		_spec.ClearField(contractsupplier.FieldAmendmentNumber, field.TypeString)
	}
	if value, ok := _u.mutation.AmendmentDate(); ok {
		_spec.SetField(contractsupplier.FieldAmendmentDate, field.TypeTime, value)
	}
	if _u.mutation.AmendmentDateCleared() {
		_spec.ClearField(contractsupplier.FieldAmendmentDate, field.TypeTime)
	}
	if value, ok := _u.mutation.AmendmentAmount(); ok {
		_spec.SetField(contractsupplier.FieldAmendmentAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmendmentAmount(); ok {
		_spec.AddField(contractsupplier.FieldAmendmentAmount, field.TypeFloat64, value)
	}
	if _u.mutation.AmendmentAmountCleared() {
		_spec.ClearField(contractsupplier.FieldAmendmentAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalWithAmendment(); ok {
		_spec.SetField(contractsupplier.FieldTotalWithAmendment, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalWithAmendment(); ok {
		_spec.AddField(contractsupplier.FieldTotalWithAmendment, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RemainingAmount(); ok {
		_spec.SetField(contractsupplier.FieldRemainingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRemainingAmount(); ok {
		_spec.AddField(contractsupplier.FieldRemainingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FileKey(); ok {
		_spec.SetField(contractsupplier.FieldFileKey, field.TypeString, value)
	}
	if _u.mutation.FileKeyCleared() {
		_spec.ClearField(contractsupplier.FieldFileKey, field.TypeString)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(contractsupplier.FieldFileName, field.TypeString, value)
	}
	if _u.mutation.FileNameCleared() {
		_spec.ClearField(contractsupplier.FieldFileName, field.TypeString)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(contractsupplier.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(contractsupplier.FieldFileSize, field.TypeInt64, value)
	}
	if _u.mutation.FileSizeCleared() {
		_spec.ClearField(contractsupplier.FieldFileSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.FileMimeType(); ok {
		_spec.SetField(contractsupplier.FieldFileMimeType, field.TypeString, value)
	}
	if _u.mutation.FileMimeTypeCleared() {
		_spec.ClearField(contractsupplier.FieldFileMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(contractsupplier.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(contractsupplier.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contractsupplier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ContractSupplierUpdateOne is the builder for updating a single ContractSupplier entity.
type ContractSupplierUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ContractSupplierMutation
}

// SetSupplierID sets the "supplier_id" field.
func (_u *ContractSupplierUpdateOne) SetSupplierID(v uuid.UUID) *ContractSupplierUpdateOne {
	_u.mutation.SetSupplierID(v)
	return _u
}

// SetNillableSupplierID sets the "supplier_id" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableSupplierID(v *uuid.UUID) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetSupplierID(*v)
	}
	return _u
}

// SetContractNumber sets the "contract_number" field.
func (_u *ContractSupplierUpdateOne) SetContractNumber(v string) *ContractSupplierUpdateOne {
	_u.mutation.SetContractNumber(v)
	return _u
}

// SetNillableContractNumber sets the "contract_number" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableContractNumber(v *string) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetContractNumber(*v)
	}
	return _u
}

// SetVatFlag sets the "vat_flag" field.
func (_u *ContractSupplierUpdateOne) SetVatFlag(v bool) *ContractSupplierUpdateOne {
	_u.mutation.SetVatFlag(v)
	return _u
}

// SetNillableVatFlag sets the "vat_flag" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableVatFlag(v *bool) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetVatFlag(*v)
	}
	return _u
}

// SetSignedDate sets the "signed_date" field.
func (_u *ContractSupplierUpdateOne) SetSignedDate(v time.Time) *ContractSupplierUpdateOne {
	_u.mutation.SetSignedDate(v)
	return _u
}

// SetNillableSignedDate sets the "signed_date" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableSignedDate(v *time.Time) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetSignedDate(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ContractSupplierUpdateOne) SetAmount(v float64) *ContractSupplierUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableAmount(v *float64) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ContractSupplierUpdateOne) AddAmount(v float64) *ContractSupplierUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetAmountCurrency sets the "amount_currency" field.
func (_u *ContractSupplierUpdateOne) SetAmountCurrency(v float64) *ContractSupplierUpdateOne {
	_u.mutation.ResetAmountCurrency()
	_u.mutation.SetAmountCurrency(v)
	return _u
}

// SetNillableAmountCurrency sets the "amount_currency" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableAmountCurrency(v *float64) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetAmountCurrency(*v)
	}
	return _u
}

// AddAmountCurrency adds value to the "amount_currency" field.
func (_u *ContractSupplierUpdateOne) AddAmountCurrency(v float64) *ContractSupplierUpdateOne {
	_u.mutation.AddAmountCurrency(v)
	return _u
}

// ClearAmountCurrency clears the value of the "amount_currency" field.
func (_u *ContractSupplierUpdateOne) ClearAmountCurrency() *ContractSupplierUpdateOne {
	_u.mutation.ClearAmountCurrency()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *ContractSupplierUpdateOne) SetCurrency(v string) *ContractSupplierUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableCurrency(v *string) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// ClearCurrency clears the value of the "currency" field.
func (_u *ContractSupplierUpdateOne) ClearCurrency() *ContractSupplierUpdateOne {
	_u.mutation.ClearCurrency()
	return _u
}

// SetBalanceAtYearEnd sets the "balance_at_year_end" field.
func (_u *ContractSupplierUpdateOne) SetBalanceAtYearEnd(v float64) *ContractSupplierUpdateOne {
	_u.mutation.ResetBalanceAtYearEnd()
	_u.mutation.SetBalanceAtYearEnd(v)
	return _u
}

// SetNillableBalanceAtYearEnd sets the "balance_at_year_end" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableBalanceAtYearEnd(v *float64) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetBalanceAtYearEnd(*v)
	}
	return _u
}

// AddBalanceAtYearEnd adds value to the "balance_at_year_end" field.
func (_u *ContractSupplierUpdateOne) AddBalanceAtYearEnd(v float64) *ContractSupplierUpdateOne {
	_u.mutation.AddBalanceAtYearEnd(v)
	return _u
}

// ClearBalanceAtYearEnd clears the value of the "balance_at_year_end" field.
func (_u *ContractSupplierUpdateOne) ClearBalanceAtYearEnd() *ContractSupplierUpdateOne {
	_u.mutation.ClearBalanceAtYearEnd()
	return _u
}

// SetAmendmentNumber sets the "amendment_number" field.
func (_u *ContractSupplierUpdateOne) SetAmendmentNumber(v string) *ContractSupplierUpdateOne {
	_u.mutation.SetAmendmentNumber(v)
	return _u
}

// SetNillableAmendmentNumber sets the "amendment_number" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableAmendmentNumber(v *string) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetAmendmentNumber(*v)
	}
	return _u
}

// ClearAmendmentNumber clears the value of the "amendment_number" field.
func (_u *ContractSupplierUpdateOne) ClearAmendmentNumber() *ContractSupplierUpdateOne {
	_u.mutation.ClearAmendmentNumber()
	return _u
}

// SetAmendmentDate sets the "amendment_date" field.
func (_u *ContractSupplierUpdateOne) SetAmendmentDate(v time.Time) *ContractSupplierUpdateOne {
	_u.mutation.SetAmendmentDate(v)
	return _u
}

// SetNillableAmendmentDate sets the "amendment_date" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableAmendmentDate(v *time.Time) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetAmendmentDate(*v)
	}
	return _u
}

// ClearAmendmentDate clears the value of the "amendment_date" field.
func (_u *ContractSupplierUpdateOne) ClearAmendmentDate() *ContractSupplierUpdateOne {
	_u.mutation.ClearAmendmentDate()
	return _u
}

// SetAmendmentAmount sets the "amendment_amount" field.
func (_u *ContractSupplierUpdateOne) SetAmendmentAmount(v float64) *ContractSupplierUpdateOne {
	_u.mutation.ResetAmendmentAmount()
	_u.mutation.SetAmendmentAmount(v)
	return _u
}

// SetNillableAmendmentAmount sets the "amendment_amount" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableAmendmentAmount(v *float64) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetAmendmentAmount(*v)
	}
	return _u
}

// AddAmendmentAmount adds value to the "amendment_amount" field.
func (_u *ContractSupplierUpdateOne) AddAmendmentAmount(v float64) *ContractSupplierUpdateOne {
	_u.mutation.AddAmendmentAmount(v)
	return _u
}

// ClearAmendmentAmount clears the value of the "amendment_amount" field.
func (_u *ContractSupplierUpdateOne) ClearAmendmentAmount() *ContractSupplierUpdateOne {
	_u.mutation.ClearAmendmentAmount()
	return _u
}

// SetTotalWithAmendment sets the "total_with_amendment" field.
func (_u *ContractSupplierUpdateOne) SetTotalWithAmendment(v float64) *ContractSupplierUpdateOne {
	_u.mutation.ResetTotalWithAmendment()
	_u.mutation.SetTotalWithAmendment(v)
	return _u
}

// SetNillableTotalWithAmendment sets the "total_with_amendment" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableTotalWithAmendment(v *float64) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetTotalWithAmendment(*v)
	}
	return _u
}

// AddTotalWithAmendment adds value to the "total_with_amendment" field.
func (_u *ContractSupplierUpdateOne) AddTotalWithAmendment(v float64) *ContractSupplierUpdateOne {
	_u.mutation.AddTotalWithAmendment(v)
	return _u
}

// SetRemainingAmount sets the "remaining_amount" field.
func (_u *ContractSupplierUpdateOne) SetRemainingAmount(v float64) *ContractSupplierUpdateOne {
	_u.mutation.ResetRemainingAmount()
	_u.mutation.SetRemainingAmount(v)
	return _u
}

// SetNillableRemainingAmount sets the "remaining_amount" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableRemainingAmount(v *float64) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetRemainingAmount(*v)
	}
	return _u
}

// AddRemainingAmount adds value to the "remaining_amount" field.
func (_u *ContractSupplierUpdateOne) AddRemainingAmount(v float64) *ContractSupplierUpdateOne {
	_u.mutation.AddRemainingAmount(v)
	return _u
}

// SetFileKey sets the "file_key" field.
func (_u *ContractSupplierUpdateOne) SetFileKey(v string) *ContractSupplierUpdateOne {
	_u.mutation.SetFileKey(v)
	return _u
}

// SetNillableFileKey sets the "file_key" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableFileKey(v *string) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetFileKey(*v)
	}
	return _u
}

// ClearFileKey clears the value of the "file_key" field.
func (_u *ContractSupplierUpdateOne) ClearFileKey() *ContractSupplierUpdateOne {
	_u.mutation.ClearFileKey()
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *ContractSupplierUpdateOne) SetFileName(v string) *ContractSupplierUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableFileName(v *string) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// ClearFileName clears the value of the "file_name" field.
func (_u *ContractSupplierUpdateOne) ClearFileName() *ContractSupplierUpdateOne {
	_u.mutation.ClearFileName()
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *ContractSupplierUpdateOne) SetFileSize(v int64) *ContractSupplierUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableFileSize(v *int64) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *ContractSupplierUpdateOne) AddFileSize(v int64) *ContractSupplierUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// ClearFileSize clears the value of the "file_size" field.
func (_u *ContractSupplierUpdateOne) ClearFileSize() *ContractSupplierUpdateOne {
	_u.mutation.ClearFileSize()
	return _u
}

// SetFileMimeType sets the "file_mime_type" field.
func (_u *ContractSupplierUpdateOne) SetFileMimeType(v string) *ContractSupplierUpdateOne {
	_u.mutation.SetFileMimeType(v)
	return _u
}

// SetNillableFileMimeType sets the "file_mime_type" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableFileMimeType(v *string) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetFileMimeType(*v)
	}
	return _u
}

// ClearFileMimeType clears the value of the "file_mime_type" field.
func (_u *ContractSupplierUpdateOne) ClearFileMimeType() *ContractSupplierUpdateOne {
	_u.mutation.ClearFileMimeType()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ContractSupplierUpdateOne) SetIsActive(v bool) *ContractSupplierUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ContractSupplierUpdateOne) SetNillableIsActive(v *bool) *ContractSupplierUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ContractSupplierUpdateOne) SetUpdatedAt(v time.Time) *ContractSupplierUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ContractSupplierMutation object of the builder.
func (_u *ContractSupplierUpdateOne) Mutation() *ContractSupplierMutation {
	return _u.mutation
}

// Where appends a list predicates to the ContractSupplierUpdate builder.
func (_u *ContractSupplierUpdateOne) Where(ps ...predicate.ContractSupplier) *ContractSupplierUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ContractSupplierUpdateOne) Select(field string, fields ...string) *ContractSupplierUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ContractSupplier entity.
func (_u *ContractSupplierUpdateOne) Save(ctx context.Context) (*ContractSupplier, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContractSupplierUpdateOne) SaveX(ctx context.Context) *ContractSupplier {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ContractSupplierUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContractSupplierUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ContractSupplierUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := contractsupplier.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContractSupplierUpdateOne) check() error {
	if v, ok := _u.mutation.ContractNumber(); ok {
		if err := contractsupplier.ContractNumberValidator(v); err != nil {
			return &ValidationError{Name: "contract_number", err: fmt.Errorf(`ent: validator failed for field "ContractSupplier.contract_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := contractsupplier.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "ContractSupplier.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmendmentNumber(); ok {
		if err := contractsupplier.AmendmentNumberValidator(v); err != nil {
			return &ValidationError{Name: "amendment_number", err: fmt.Errorf(`ent: validator failed for field "ContractSupplier.amendment_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileKey(); ok {
		if err := contractsupplier.FileKeyValidator(v); err != nil {
			return &ValidationError{Name: "file_key", err: fmt.Errorf(`ent: validator failed for field "ContractSupplier.file_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := contractsupplier.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "ContractSupplier.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileMimeType(); ok {
		if err := contractsupplier.FileMimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "file_mime_type", err: fmt.Errorf(`ent: validator failed for field "ContractSupplier.file_mime_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ContractSupplierUpdateOne) sqlSave(ctx context.Context) (_node *ContractSupplier, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contractsupplier.Table, contractsupplier.Columns, sqlgraph.NewFieldSpec(contractsupplier.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ContractSupplier.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contractsupplier.FieldID)
		for _, f := range fields {
			if !contractsupplier.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != contractsupplier.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SupplierID(); ok {
		_spec.SetField(contractsupplier.FieldSupplierID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ContractNumber(); ok {
		_spec.SetField(contractsupplier.FieldContractNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.VatFlag(); ok {
		_spec.SetField(contractsupplier.FieldVatFlag, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SignedDate(); ok {
		_spec.SetField(contractsupplier.FieldSignedDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(contractsupplier.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(contractsupplier.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AmountCurrency(); ok {
		_spec.SetField(contractsupplier.FieldAmountCurrency, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCurrency(); ok {
		_spec.AddField(contractsupplier.FieldAmountCurrency, field.TypeFloat64, value)
	}
	if _u.mutation.AmountCurrencyCleared() {
		_spec.ClearField(contractsupplier.FieldAmountCurrency, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(contractsupplier.FieldCurrency, field.TypeString, value)
	}
	if _u.mutation.CurrencyCleared() {
		_spec.ClearField(contractsupplier.FieldCurrency, field.TypeString)
	}
	if value, ok := _u.mutation.BalanceAtYearEnd(); ok {
		_spec.SetField(contractsupplier.FieldBalanceAtYearEnd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAtYearEnd(); ok {
		_spec.AddField(contractsupplier.FieldBalanceAtYearEnd, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceAtYearEndCleared() {
		_spec.ClearField(contractsupplier.FieldBalanceAtYearEnd, field.TypeFloat64)
	}
	if value, ok := _u.mutation.AmendmentNumber(); ok {
		_spec.SetField(contractsupplier.FieldAmendmentNumber, field.TypeString, value)
	}
	if _u.mutation.AmendmentNumberCleared() {
		_spec.ClearField(contractsupplier.FieldAmendmentNumber, field.TypeString)
	}
	if value, ok := _u.mutation.AmendmentDate(); ok {
		_spec.SetField(contractsupplier.FieldAmendmentDate, field.TypeTime, value)
	}
	if _u.mutation.AmendmentDateCleared() {
		_spec.ClearField(contractsupplier.FieldAmendmentDate, field.TypeTime)
	}
	if value, ok := _u.mutation.AmendmentAmount(); ok {
		_spec.SetField(contractsupplier.FieldAmendmentAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmendmentAmount(); ok {
		_spec.AddField(contractsupplier.FieldAmendmentAmount, field.TypeFloat64, value)
	}
	if _u.mutation.AmendmentAmountCleared() {
		_spec.ClearField(contractsupplier.FieldAmendmentAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.TotalWithAmendment(); ok {
		_spec.SetField(contractsupplier.FieldTotalWithAmendment, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalWithAmendment(); ok {
		_spec.AddField(contractsupplier.FieldTotalWithAmendment, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RemainingAmount(); ok {
		_spec.SetField(contractsupplier.FieldRemainingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRemainingAmount(); ok {
		_spec.AddField(contractsupplier.FieldRemainingAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FileKey(); ok {
		_spec.SetField(contractsupplier.FieldFileKey, field.TypeString, value)
	}
	if _u.mutation.FileKeyCleared() {
		_spec.ClearField(contractsupplier.FieldFileKey, field.TypeString)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(contractsupplier.FieldFileName, field.TypeString, value)
	}
	if _u.mutation.FileNameCleared() {
		_spec.ClearField(contractsupplier.FieldFileName, field.TypeString)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(contractsupplier.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(contractsupplier.FieldFileSize, field.TypeInt64, value)
	}
	if _u.mutation.FileSizeCleared() {
		_spec.ClearField(contractsupplier.FieldFileSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.FileMimeType(); ok {
		_spec.SetField(contractsupplier.FieldFileMimeType, field.TypeString, value)
	}
	if _u.mutation.FileMimeTypeCleared() {
		_spec.ClearField(contractsupplier.FieldFileMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(contractsupplier.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(contractsupplier.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ContractSupplier{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contractsupplier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
