// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"encore.app/db/ent/contractsupplierhistory"
	"encore.app/db/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ContractSupplierHistoryUpdate is the builder for updating ContractSupplierHistory entities.
type ContractSupplierHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *ContractSupplierHistoryMutation
}

// Where appends a list predicates to the ContractSupplierHistoryUpdate builder.
func (_u *ContractSupplierHistoryUpdate) Where(ps ...predicate.ContractSupplierHistory) *ContractSupplierHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContractID sets the "contract_id" field.
func (_u *ContractSupplierHistoryUpdate) SetContractID(v uuid.UUID) *ContractSupplierHistoryUpdate {
	_u.mutation.SetContractID(v)
	return _u
}

// SetNillableContractID sets the "contract_id" field if the given value is not nil.
func (_u *ContractSupplierHistoryUpdate) SetNillableContractID(v *uuid.UUID) *ContractSupplierHistoryUpdate {
	if v != nil {
		_u.SetContractID(*v)
	}
	return _u
}

// SetOperationType sets the "operation_type" field.
func (_u *ContractSupplierHistoryUpdate) SetOperationType(v string) *ContractSupplierHistoryUpdate {
	_u.mutation.SetOperationType(v)
	return _u
}

// SetNillableOperationType sets the "operation_type" field if the given value is not nil.
func (_u *ContractSupplierHistoryUpdate) SetNillableOperationType(v *string) *ContractSupplierHistoryUpdate {
	if v != nil {
		_u.SetOperationType(*v)
	}
	return _u
}

// SetChangedBy sets the "changed_by" field.
func (_u *ContractSupplierHistoryUpdate) SetChangedBy(v uuid.UUID) *ContractSupplierHistoryUpdate {
	_u.mutation.SetChangedBy(v)
	return _u
}

// SetNillableChangedBy sets the "changed_by" field if the given value is not nil.
func (_u *ContractSupplierHistoryUpdate) SetNillableChangedBy(v *uuid.UUID) *ContractSupplierHistoryUpdate {
	if v != nil {
		_u.SetChangedBy(*v)
	}
	return _u
}

// ClearChangedBy clears the value of the "changed_by" field.
func (_u *ContractSupplierHistoryUpdate) ClearChangedBy() *ContractSupplierHistoryUpdate {
	_u.mutation.ClearChangedBy()
	return _u
}

// SetSnapshot sets the "snapshot" field.
func (_u *ContractSupplierHistoryUpdate) SetSnapshot(v map[string]interface{}) *ContractSupplierHistoryUpdate {
	_u.mutation.SetSnapshot(v)
	return _u
}

// ClearSnapshot clears the value of the "snapshot" field.
func (_u *ContractSupplierHistoryUpdate) ClearSnapshot() *ContractSupplierHistoryUpdate {
	_u.mutation.ClearSnapshot()
	return _u
}

// SetDiff sets the "diff" field.
func (_u *ContractSupplierHistoryUpdate) SetDiff(v map[string]interface{}) *ContractSupplierHistoryUpdate {
	_u.mutation.SetDiff(v)
	return _u
}

// ClearDiff clears the value of the "diff" field.
func (_u *ContractSupplierHistoryUpdate) ClearDiff() *ContractSupplierHistoryUpdate {
	_u.mutation.ClearDiff()
	return _u
}

// Mutation returns the ContractSupplierHistoryMutation object of the builder.
func (_u *ContractSupplierHistoryUpdate) Mutation() *ContractSupplierHistoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ContractSupplierHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContractSupplierHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ContractSupplierHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContractSupplierHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContractSupplierHistoryUpdate) check() error {
	if v, ok := _u.mutation.OperationType(); ok {
		if err := contractsupplierhistory.OperationTypeValidator(v); err != nil {
			return &ValidationError{Name: "operation_type", err: fmt.Errorf(`ent: validator failed for field "ContractSupplierHistory.operation_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ContractSupplierHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contractsupplierhistory.Table, contractsupplierhistory.Columns, sqlgraph.NewFieldSpec(contractsupplierhistory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ContractID(); ok {
		_spec.SetField(contractsupplierhistory.FieldContractID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.OperationType(); ok {
		_spec.SetField(contractsupplierhistory.FieldOperationType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChangedBy(); ok {
		_spec.SetField(contractsupplierhistory.FieldChangedBy, field.TypeUUID, value)
	}
	if _u.mutation.ChangedByCleared() {
		_spec.ClearField(contractsupplierhistory.FieldChangedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.Snapshot(); ok {
		_spec.SetField(contractsupplierhistory.FieldSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.SnapshotCleared() {
		_spec.ClearField(contractsupplierhistory.FieldSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.Diff(); ok {
		_spec.SetField(contractsupplierhistory.FieldDiff, field.TypeJSON, value)
	}
	if _u.mutation.DiffCleared() {
		_spec.ClearField(contractsupplierhistory.FieldDiff, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contractsupplierhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ContractSupplierHistoryUpdateOne is the builder for updating a single ContractSupplierHistory entity.
type ContractSupplierHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ContractSupplierHistoryMutation
}

// SetContractID sets the "contract_id" field.
func (_u *ContractSupplierHistoryUpdateOne) SetContractID(v uuid.UUID) *ContractSupplierHistoryUpdateOne {
	_u.mutation.SetContractID(v)
	return _u
}

// SetNillableContractID sets the "contract_id" field if the given value is not nil.
func (_u *ContractSupplierHistoryUpdateOne) SetNillableContractID(v *uuid.UUID) *ContractSupplierHistoryUpdateOne {
	if v != nil {
		_u.SetContractID(*v)
	}
	return _u
}

// SetOperationType sets the "operation_type" field.
func (_u *ContractSupplierHistoryUpdateOne) SetOperationType(v string) *ContractSupplierHistoryUpdateOne {
	_u.mutation.SetOperationType(v)
	return _u
}

// SetNillableOperationType sets the "operation_type" field if the given value is not nil.
func (_u *ContractSupplierHistoryUpdateOne) SetNillableOperationType(v *string) *ContractSupplierHistoryUpdateOne {
	if v != nil {
		_u.SetOperationType(*v)
	}
	return _u
}

// SetChangedBy sets the "changed_by" field.
func (_u *ContractSupplierHistoryUpdateOne) SetChangedBy(v uuid.UUID) *ContractSupplierHistoryUpdateOne {
	_u.mutation.SetChangedBy(v)
	return _u
}

// SetNillableChangedBy sets the "changed_by" field if the given value is not nil.
func (_u *ContractSupplierHistoryUpdateOne) SetNillableChangedBy(v *uuid.UUID) *ContractSupplierHistoryUpdateOne {
	if v != nil {
		_u.SetChangedBy(*v)
	}
	return _u
}

// ClearChangedBy clears the value of the "changed_by" field.
func (_u *ContractSupplierHistoryUpdateOne) ClearChangedBy() *ContractSupplierHistoryUpdateOne {
	_u.mutation.ClearChangedBy()
	return _u
}

// SetSnapshot sets the "snapshot" field.
func (_u *ContractSupplierHistoryUpdateOne) SetSnapshot(v map[string]interface{}) *ContractSupplierHistoryUpdateOne {
	_u.mutation.SetSnapshot(v)
	return _u
}

// ClearSnapshot clears the value of the "snapshot" field.
func (_u *ContractSupplierHistoryUpdateOne) ClearSnapshot() *ContractSupplierHistoryUpdateOne {
	_u.mutation.ClearSnapshot()
	return _u
}

// SetDiff sets the "diff" field.
func (_u *ContractSupplierHistoryUpdateOne) SetDiff(v map[string]interface{}) *ContractSupplierHistoryUpdateOne {
	_u.mutation.SetDiff(v)
	return _u
}

// ClearDiff clears the value of the "diff" field.
func (_u *ContractSupplierHistoryUpdateOne) ClearDiff() *ContractSupplierHistoryUpdateOne {
	_u.mutation.ClearDiff()
	return _u
}

// Mutation returns the ContractSupplierHistoryMutation object of the builder.
func (_u *ContractSupplierHistoryUpdateOne) Mutation() *ContractSupplierHistoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the ContractSupplierHistoryUpdate builder.
func (_u *ContractSupplierHistoryUpdateOne) Where(ps ...predicate.ContractSupplierHistory) *ContractSupplierHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ContractSupplierHistoryUpdateOne) Select(field string, fields ...string) *ContractSupplierHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ContractSupplierHistory entity.
func (_u *ContractSupplierHistoryUpdateOne) Save(ctx context.Context) (*ContractSupplierHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContractSupplierHistoryUpdateOne) SaveX(ctx context.Context) *ContractSupplierHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ContractSupplierHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContractSupplierHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContractSupplierHistoryUpdateOne) check() error {
	if v, ok := _u.mutation.OperationType(); ok {
		if err := contractsupplierhistory.OperationTypeValidator(v); err != nil {
			return &ValidationError{Name: "operation_type", err: fmt.Errorf(`ent: validator failed for field "ContractSupplierHistory.operation_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ContractSupplierHistoryUpdateOne) sqlSave(ctx context.Context) (_node *ContractSupplierHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contractsupplierhistory.Table, contractsupplierhistory.Columns, sqlgraph.NewFieldSpec(contractsupplierhistory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ContractSupplierHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contractsupplierhistory.FieldID)
		for _, f := range fields {
			if !contractsupplierhistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != contractsupplierhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ContractID(); ok {
		_spec.SetField(contractsupplierhistory.FieldContractID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.OperationType(); ok {
		_spec.SetField(contractsupplierhistory.FieldOperationType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChangedBy(); ok {
		_spec.SetField(contractsupplierhistory.FieldChangedBy, field.TypeUUID, value)
	}
	if _u.mutation.ChangedByCleared() {
		_spec.ClearField(contractsupplierhistory.FieldChangedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.Snapshot(); ok {
		_spec.SetField(contractsupplierhistory.FieldSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.SnapshotCleared() {
		_spec.ClearField(contractsupplierhistory.FieldSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.Diff(); ok {
		_spec.SetField(contractsupplierhistory.FieldDiff, field.TypeJSON, value)
	}
	if _u.mutation.DiffCleared() {
		_spec.ClearField(contractsupplierhistory.FieldDiff, field.TypeJSON)
	}
	_node = &ContractSupplierHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contractsupplierhistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
