// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"encore.app/db/ent/dzoorganization"
	"encore.app/db/ent/employee"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DzoOrganizationCreate is the builder for creating a DzoOrganization entity.
type DzoOrganizationCreate struct {
	config
	mutation *DzoOrganizationMutation
	hooks    []Hook
}

// SetClientID sets the "client_id" field.
func (_c *DzoOrganizationCreate) SetClientID(v uuid.UUID) *DzoOrganizationCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DzoOrganizationCreate) SetName(v string) *DzoOrganizationCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetShortName sets the "short_name" field.
func (_c *DzoOrganizationCreate) SetShortName(v string) *DzoOrganizationCreate {
	_c.mutation.SetShortName(v)
	return _c
}

// SetNillableShortName sets the "short_name" field if the given value is not nil.
func (_c *DzoOrganizationCreate) SetNillableShortName(v *string) *DzoOrganizationCreate {
	if v != nil {
		_c.SetShortName(*v)
	}
	return _c
}

// SetBin sets the "bin" field.
func (_c *DzoOrganizationCreate) SetBin(v string) *DzoOrganizationCreate {
	_c.mutation.SetBin(v)
	return _c
}

// SetNillableBin sets the "bin" field if the given value is not nil.
func (_c *DzoOrganizationCreate) SetNillableBin(v *string) *DzoOrganizationCreate {
	if v != nil {
		_c.SetBin(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *DzoOrganizationCreate) SetIsActive(v bool) *DzoOrganizationCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *DzoOrganizationCreate) SetNillableIsActive(v *bool) *DzoOrganizationCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DzoOrganizationCreate) SetID(v uuid.UUID) *DzoOrganizationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DzoOrganizationCreate) SetNillableID(v *uuid.UUID) *DzoOrganizationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddEmployeeIDs adds the "employees" edge to the Employee entity by IDs.
func (_c *DzoOrganizationCreate) AddEmployeeIDs(ids ...uuid.UUID) *DzoOrganizationCreate {
	_c.mutation.AddEmployeeIDs(ids...)
	return _c
}

// AddEmployees adds the "employees" edges to the Employee entity.
func (_c *DzoOrganizationCreate) AddEmployees(v ...*Employee) *DzoOrganizationCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEmployeeIDs(ids...)
}

// Mutation returns the DzoOrganizationMutation object of the builder.
func (_c *DzoOrganizationCreate) Mutation() *DzoOrganizationMutation {
	return _c.mutation
}

// Save creates the DzoOrganization in the database.
func (_c *DzoOrganizationCreate) Save(ctx context.Context) (*DzoOrganization, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DzoOrganizationCreate) SaveX(ctx context.Context) *DzoOrganization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DzoOrganizationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DzoOrganizationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DzoOrganizationCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := dzoorganization.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := dzoorganization.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DzoOrganizationCreate) check() error {
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "DzoOrganization.client_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DzoOrganization.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := dzoorganization.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DzoOrganization.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ShortName(); ok {
		if err := dzoorganization.ShortNameValidator(v); err != nil {
			return &ValidationError{Name: "short_name", err: fmt.Errorf(`ent: validator failed for field "DzoOrganization.short_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Bin(); ok {
		if err := dzoorganization.BinValidator(v); err != nil {
			return &ValidationError{Name: "bin", err: fmt.Errorf(`ent: validator failed for field "DzoOrganization.bin": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "DzoOrganization.is_active"`)}
	}
	return nil
}

func (_c *DzoOrganizationCreate) sqlSave(ctx context.Context) (*DzoOrganization, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DzoOrganizationCreate) createSpec() (*DzoOrganization, *sqlgraph.CreateSpec) {
	var (
		_node = &DzoOrganization{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dzoorganization.Table, sqlgraph.NewFieldSpec(dzoorganization.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(dzoorganization.FieldClientID, field.TypeUUID, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(dzoorganization.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ShortName(); ok {
		_spec.SetField(dzoorganization.FieldShortName, field.TypeString, value)
		_node.ShortName = &value
	}
	if value, ok := _c.mutation.Bin(); ok {
		_spec.SetField(dzoorganization.FieldBin, field.TypeString, value)
		_node.Bin = &value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(dzoorganization.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if nodes := _c.mutation.EmployeesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   dzoorganization.EmployeesTable,
			Columns: []string{dzoorganization.EmployeesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DzoOrganizationCreateBulk is the builder for creating many DzoOrganization entities in bulk.
type DzoOrganizationCreateBulk struct {
	config
	err      error
	builders []*DzoOrganizationCreate
}

// Save creates the DzoOrganization entities in the database.
func (_c *DzoOrganizationCreateBulk) Save(ctx context.Context) ([]*DzoOrganization, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DzoOrganization, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DzoOrganizationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DzoOrganizationCreateBulk) SaveX(ctx context.Context) []*DzoOrganization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DzoOrganizationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DzoOrganizationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
