// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"encore.app/db/ent/dzoorganization"
	"encore.app/db/ent/dzopositiontitle"
	"encore.app/db/ent/employee"
	"encore.app/db/ent/generalposition"
	"encore.app/db/ent/predicate"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// DzoPositionTitleQuery is the builder for querying DzoPositionTitle entities.
type DzoPositionTitleQuery struct {
	config
	ctx                 *QueryContext
	order               []dzopositiontitle.OrderOption
	inters              []Interceptor
	predicates          []predicate.DzoPositionTitle
	withDzo             *DzoOrganizationQuery
	withGeneralPosition *GeneralPositionQuery
	withEmployees       *EmployeeQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DzoPositionTitleQuery builder.
func (_q *DzoPositionTitleQuery) Where(ps ...predicate.DzoPositionTitle) *DzoPositionTitleQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DzoPositionTitleQuery) Limit(limit int) *DzoPositionTitleQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DzoPositionTitleQuery) Offset(offset int) *DzoPositionTitleQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DzoPositionTitleQuery) Unique(unique bool) *DzoPositionTitleQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DzoPositionTitleQuery) Order(o ...dzopositiontitle.OrderOption) *DzoPositionTitleQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDzo chains the current query on the "dzo" edge.
func (_q *DzoPositionTitleQuery) QueryDzo() *DzoOrganizationQuery {
	query := (&DzoOrganizationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dzopositiontitle.Table, dzopositiontitle.FieldID, selector),
			sqlgraph.To(dzoorganization.Table, dzoorganization.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, dzopositiontitle.DzoTable, dzopositiontitle.DzoColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGeneralPosition chains the current query on the "general_position" edge.
func (_q *DzoPositionTitleQuery) QueryGeneralPosition() *GeneralPositionQuery {
	query := (&GeneralPositionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dzopositiontitle.Table, dzopositiontitle.FieldID, selector),
			sqlgraph.To(generalposition.Table, generalposition.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, dzopositiontitle.GeneralPositionTable, dzopositiontitle.GeneralPositionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEmployees chains the current query on the "employees" edge.
func (_q *DzoPositionTitleQuery) QueryEmployees() *EmployeeQuery {
	query := (&EmployeeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dzopositiontitle.Table, dzopositiontitle.FieldID, selector),
			sqlgraph.To(employee.Table, employee.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, dzopositiontitle.EmployeesTable, dzopositiontitle.EmployeesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DzoPositionTitle entity from the query.
// Returns a *NotFoundError when no DzoPositionTitle was found.
func (_q *DzoPositionTitleQuery) First(ctx context.Context) (*DzoPositionTitle, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dzopositiontitle.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DzoPositionTitleQuery) FirstX(ctx context.Context) *DzoPositionTitle {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DzoPositionTitle ID from the query.
// Returns a *NotFoundError when no DzoPositionTitle ID was found.
func (_q *DzoPositionTitleQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{dzopositiontitle.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *DzoPositionTitleQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DzoPositionTitle entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DzoPositionTitle entity is found.
// Returns a *NotFoundError when no DzoPositionTitle entities are found.
func (_q *DzoPositionTitleQuery) Only(ctx context.Context) (*DzoPositionTitle, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dzopositiontitle.Label}
	default:
		return nil, &NotSingularError{dzopositiontitle.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DzoPositionTitleQuery) OnlyX(ctx context.Context) *DzoPositionTitle {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DzoPositionTitle ID in the query.
// Returns a *NotSingularError when more than one DzoPositionTitle ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *DzoPositionTitleQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{dzopositiontitle.Label}
	default:
		err = &NotSingularError{dzopositiontitle.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *DzoPositionTitleQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DzoPositionTitles.
func (_q *DzoPositionTitleQuery) All(ctx context.Context) ([]*DzoPositionTitle, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DzoPositionTitle, *DzoPositionTitleQuery]()
	return withInterceptors[[]*DzoPositionTitle](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DzoPositionTitleQuery) AllX(ctx context.Context) []*DzoPositionTitle {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DzoPositionTitle IDs.
func (_q *DzoPositionTitleQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(dzopositiontitle.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *DzoPositionTitleQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *DzoPositionTitleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DzoPositionTitleQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DzoPositionTitleQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DzoPositionTitleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DzoPositionTitleQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DzoPositionTitleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DzoPositionTitleQuery) Clone() *DzoPositionTitleQuery {
	if _q == nil {
		return nil
	}
	return &DzoPositionTitleQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]dzopositiontitle.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.DzoPositionTitle{}, _q.predicates...),
		withDzo:             _q.withDzo.Clone(),
		withGeneralPosition: _q.withGeneralPosition.Clone(),
		withEmployees:       _q.withEmployees.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithDzo tells the query-builder to eager-load the nodes that are connected to
// the "dzo" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DzoPositionTitleQuery) WithDzo(opts ...func(*DzoOrganizationQuery)) *DzoPositionTitleQuery {
	query := (&DzoOrganizationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDzo = query
	return _q
}

// WithGeneralPosition tells the query-builder to eager-load the nodes that are connected to
// the "general_position" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DzoPositionTitleQuery) WithGeneralPosition(opts ...func(*GeneralPositionQuery)) *DzoPositionTitleQuery {
	query := (&GeneralPositionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGeneralPosition = query
	return _q
}

// WithEmployees tells the query-builder to eager-load the nodes that are connected to
// the "employees" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DzoPositionTitleQuery) WithEmployees(opts ...func(*EmployeeQuery)) *DzoPositionTitleQuery {
	query := (&EmployeeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEmployees = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DzoID uuid.UUID `json:"dzo_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DzoPositionTitle.Query().
//		GroupBy(dzopositiontitle.FieldDzoID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DzoPositionTitleQuery) GroupBy(field string, fields ...string) *DzoPositionTitleGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DzoPositionTitleGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = dzopositiontitle.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DzoID uuid.UUID `json:"dzo_id,omitempty"`
//	}
//
//	client.DzoPositionTitle.Query().
//		Select(dzopositiontitle.FieldDzoID).
//		Scan(ctx, &v)
func (_q *DzoPositionTitleQuery) Select(fields ...string) *DzoPositionTitleSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DzoPositionTitleSelect{DzoPositionTitleQuery: _q}
	sbuild.label = dzopositiontitle.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DzoPositionTitleSelect configured with the given aggregations.
func (_q *DzoPositionTitleQuery) Aggregate(fns ...AggregateFunc) *DzoPositionTitleSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DzoPositionTitleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !dzopositiontitle.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DzoPositionTitleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DzoPositionTitle, error) {
	var (
		nodes       = []*DzoPositionTitle{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withDzo != nil,
			_q.withGeneralPosition != nil,
			_q.withEmployees != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DzoPositionTitle).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DzoPositionTitle{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDzo; query != nil {
		if err := _q.loadDzo(ctx, query, nodes, nil,
			func(n *DzoPositionTitle, e *DzoOrganization) { n.Edges.Dzo = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGeneralPosition; query != nil {
		if err := _q.loadGeneralPosition(ctx, query, nodes, nil,
			func(n *DzoPositionTitle, e *GeneralPosition) { n.Edges.GeneralPosition = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEmployees; query != nil {
		if err := _q.loadEmployees(ctx, query, nodes,
			func(n *DzoPositionTitle) { n.Edges.Employees = []*Employee{} },
			func(n *DzoPositionTitle, e *Employee) { n.Edges.Employees = append(n.Edges.Employees, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DzoPositionTitleQuery) loadDzo(ctx context.Context, query *DzoOrganizationQuery, nodes []*DzoPositionTitle, init func(*DzoPositionTitle), assign func(*DzoPositionTitle, *DzoOrganization)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*DzoPositionTitle)
	for i := range nodes {
		fk := nodes[i].DzoID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(dzoorganization.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "dzo_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DzoPositionTitleQuery) loadGeneralPosition(ctx context.Context, query *GeneralPositionQuery, nodes []*DzoPositionTitle, init func(*DzoPositionTitle), assign func(*DzoPositionTitle, *GeneralPosition)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*DzoPositionTitle)
	for i := range nodes {
		if nodes[i].GeneralPositionID == nil {
			continue
		}
		fk := *nodes[i].GeneralPositionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(generalposition.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "general_position_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DzoPositionTitleQuery) loadEmployees(ctx context.Context, query *EmployeeQuery, nodes []*DzoPositionTitle, init func(*DzoPositionTitle), assign func(*DzoPositionTitle, *Employee)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*DzoPositionTitle)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(employee.FieldDzoPositionID)
	}
	query.Where(predicate.Employee(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(dzopositiontitle.EmployeesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.DzoPositionID
		if fk == nil {
			return fmt.Errorf(`foreign-key "dzo_position_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "dzo_position_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *DzoPositionTitleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DzoPositionTitleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(dzopositiontitle.Table, dzopositiontitle.Columns, sqlgraph.NewFieldSpec(dzopositiontitle.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dzopositiontitle.FieldID)
		for i := range fields {
			if fields[i] != dzopositiontitle.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withDzo != nil {
			_spec.Node.AddColumnOnce(dzopositiontitle.FieldDzoID)
		}
		if _q.withGeneralPosition != nil {
			_spec.Node.AddColumnOnce(dzopositiontitle.FieldGeneralPositionID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DzoPositionTitleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(dzopositiontitle.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = dzopositiontitle.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DzoPositionTitleGroupBy is the group-by builder for DzoPositionTitle entities.
type DzoPositionTitleGroupBy struct {
	selector
	build *DzoPositionTitleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DzoPositionTitleGroupBy) Aggregate(fns ...AggregateFunc) *DzoPositionTitleGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DzoPositionTitleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DzoPositionTitleQuery, *DzoPositionTitleGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DzoPositionTitleGroupBy) sqlScan(ctx context.Context, root *DzoPositionTitleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DzoPositionTitleSelect is the builder for selecting fields of DzoPositionTitle entities.
type DzoPositionTitleSelect struct {
	*DzoPositionTitleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DzoPositionTitleSelect) Aggregate(fns ...AggregateFunc) *DzoPositionTitleSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DzoPositionTitleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DzoPositionTitleQuery, *DzoPositionTitleSelect](ctx, _s.DzoPositionTitleQuery, _s, _s.inters, v)
}

func (_s *DzoPositionTitleSelect) sqlScan(ctx context.Context, root *DzoPositionTitleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
