// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"encore.app/db/ent/dzoorganization"
	"encore.app/db/ent/dzopositiontitle"
	"encore.app/db/ent/generalposition"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// DzoPositionTitle is the model entity for the DzoPositionTitle schema.
type DzoPositionTitle struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DzoID holds the value of the "dzo_id" field.
	DzoID uuid.UUID `json:"dzo_id,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID uuid.UUID `json:"client_id,omitempty"`
	// GeneralPositionID holds the value of the "general_position_id" field.
	GeneralPositionID *uuid.UUID `json:"general_position_id,omitempty"`
	// LocalTitle holds the value of the "local_title" field.
	LocalTitle string `json:"local_title,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// IsDeleted holds the value of the "is_deleted" field.
	IsDeleted bool `json:"is_deleted,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DzoPositionTitleQuery when eager-loading is set.
	Edges        DzoPositionTitleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DzoPositionTitleEdges holds the relations/edges for other nodes in the graph.
type DzoPositionTitleEdges struct {
	// Dzo holds the value of the dzo edge.
	Dzo *DzoOrganization `json:"dzo,omitempty"`
	// GeneralPosition holds the value of the general_position edge.
	GeneralPosition *GeneralPosition `json:"general_position,omitempty"`
	// Employees holds the value of the employees edge.
	Employees []*Employee `json:"employees,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// DzoOrErr returns the Dzo value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DzoPositionTitleEdges) DzoOrErr() (*DzoOrganization, error) {
	if e.Dzo != nil {
		return e.Dzo, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: dzoorganization.Label}
	}
	return nil, &NotLoadedError{edge: "dzo"}
}

// GeneralPositionOrErr returns the GeneralPosition value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DzoPositionTitleEdges) GeneralPositionOrErr() (*GeneralPosition, error) {
	if e.GeneralPosition != nil {
		return e.GeneralPosition, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: generalposition.Label}
	}
	return nil, &NotLoadedError{edge: "general_position"}
}

// EmployeesOrErr returns the Employees value or an error if the edge
// was not loaded in eager-loading.
func (e DzoPositionTitleEdges) EmployeesOrErr() ([]*Employee, error) {
	if e.loadedTypes[2] {
		return e.Employees, nil
	}
	return nil, &NotLoadedError{edge: "employees"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DzoPositionTitle) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dzopositiontitle.FieldGeneralPositionID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case dzopositiontitle.FieldIsActive, dzopositiontitle.FieldIsDeleted:
			values[i] = new(sql.NullBool)
		case dzopositiontitle.FieldLocalTitle:
			values[i] = new(sql.NullString)
		case dzopositiontitle.FieldCreatedAt, dzopositiontitle.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case dzopositiontitle.FieldID, dzopositiontitle.FieldDzoID, dzopositiontitle.FieldClientID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DzoPositionTitle fields.
func (_m *DzoPositionTitle) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dzopositiontitle.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case dzopositiontitle.FieldDzoID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field dzo_id", values[i])
			} else if value != nil {
				_m.DzoID = *value
			}
		case dzopositiontitle.FieldClientID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value != nil {
				_m.ClientID = *value
			}
		case dzopositiontitle.FieldGeneralPositionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field general_position_id", values[i])
			} else if value.Valid {
				_m.GeneralPositionID = new(uuid.UUID)
				*_m.GeneralPositionID = *value.S.(*uuid.UUID)
			}
		case dzopositiontitle.FieldLocalTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_title", values[i])
			} else if value.Valid {
				_m.LocalTitle = value.String
			}
		case dzopositiontitle.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case dzopositiontitle.FieldIsDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_deleted", values[i])
			} else if value.Valid {
				_m.IsDeleted = value.Bool
			}
		case dzopositiontitle.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case dzopositiontitle.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DzoPositionTitle.
// This includes values selected through modifiers, order, etc.
func (_m *DzoPositionTitle) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDzo queries the "dzo" edge of the DzoPositionTitle entity.
func (_m *DzoPositionTitle) QueryDzo() *DzoOrganizationQuery {
	return NewDzoPositionTitleClient(_m.config).QueryDzo(_m)
}

// QueryGeneralPosition queries the "general_position" edge of the DzoPositionTitle entity.
func (_m *DzoPositionTitle) QueryGeneralPosition() *GeneralPositionQuery {
	return NewDzoPositionTitleClient(_m.config).QueryGeneralPosition(_m)
}

// QueryEmployees queries the "employees" edge of the DzoPositionTitle entity.
func (_m *DzoPositionTitle) QueryEmployees() *EmployeeQuery {
	return NewDzoPositionTitleClient(_m.config).QueryEmployees(_m)
}

// Update returns a builder for updating this DzoPositionTitle.
// Note that you need to call DzoPositionTitle.Unwrap() before calling this method if this DzoPositionTitle
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DzoPositionTitle) Update() *DzoPositionTitleUpdateOne {
	return NewDzoPositionTitleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DzoPositionTitle entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DzoPositionTitle) Unwrap() *DzoPositionTitle {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DzoPositionTitle is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DzoPositionTitle) String() string {
	var builder strings.Builder
	builder.WriteString("DzoPositionTitle(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("dzo_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DzoID))
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientID))
	builder.WriteString(", ")
	if v := _m.GeneralPositionID; v != nil {
		builder.WriteString("general_position_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("local_title=")
	builder.WriteString(_m.LocalTitle)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("is_deleted=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDeleted))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DzoPositionTitles is a parsable slice of DzoPositionTitle.
type DzoPositionTitles []*DzoPositionTitle
