// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"encore.app/db/ent/dzoorganization"
	"encore.app/db/ent/dzopositiontitle"
	"encore.app/db/ent/employee"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Employee is the model entity for the Employee schema.
type Employee struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID uuid.UUID `json:"client_id,omitempty"`
	// DzoID holds the value of the "dzo_id" field.
	DzoID uuid.UUID `json:"dzo_id,omitempty"`
	// DzoPositionID holds the value of the "dzo_position_id" field.
	DzoPositionID *uuid.UUID `json:"dzo_position_id,omitempty"`
	// FullName holds the value of the "full_name" field.
	FullName string `json:"full_name,omitempty"`
	// ShortName holds the value of the "short_name" field.
	ShortName *string `json:"short_name,omitempty"`
	// Department holds the value of the "department" field.
	Department *string `json:"department,omitempty"`
	// Direction holds the value of the "direction" field.
	Direction *string `json:"direction,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// InternalPhone holds the value of the "internal_phone" field.
	InternalPhone *string `json:"internal_phone,omitempty"`
	// BirthDate holds the value of the "birth_date" field.
	BirthDate *time.Time `json:"birth_date,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *uuid.UUID `json:"user_id,omitempty"`
	// IsDeleted holds the value of the "is_deleted" field.
	IsDeleted bool `json:"is_deleted,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EmployeeQuery when eager-loading is set.
	Edges        EmployeeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EmployeeEdges holds the relations/edges for other nodes in the graph.
type EmployeeEdges struct {
	// Dzo holds the value of the dzo edge.
	Dzo *DzoOrganization `json:"dzo,omitempty"`
	// DzoPositionTitle holds the value of the dzo_position_title edge.
	DzoPositionTitle *DzoPositionTitle `json:"dzo_position_title,omitempty"`
	// EventParticipations holds the value of the event_participations edge.
	EventParticipations []*EventParticipant `json:"event_participations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// DzoOrErr returns the Dzo value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EmployeeEdges) DzoOrErr() (*DzoOrganization, error) {
	if e.Dzo != nil {
		return e.Dzo, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: dzoorganization.Label}
	}
	return nil, &NotLoadedError{edge: "dzo"}
}

// DzoPositionTitleOrErr returns the DzoPositionTitle value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EmployeeEdges) DzoPositionTitleOrErr() (*DzoPositionTitle, error) {
	if e.DzoPositionTitle != nil {
		return e.DzoPositionTitle, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: dzopositiontitle.Label}
	}
	return nil, &NotLoadedError{edge: "dzo_position_title"}
}

// EventParticipationsOrErr returns the EventParticipations value or an error if the edge
// was not loaded in eager-loading.
func (e EmployeeEdges) EventParticipationsOrErr() ([]*EventParticipant, error) {
	if e.loadedTypes[2] {
		return e.EventParticipations, nil
	}
	return nil, &NotLoadedError{edge: "event_participations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Employee) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case employee.FieldDzoPositionID, employee.FieldUserID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case employee.FieldIsActive, employee.FieldIsDeleted:
			values[i] = new(sql.NullBool)
		case employee.FieldFullName, employee.FieldShortName, employee.FieldDepartment, employee.FieldDirection, employee.FieldEmail, employee.FieldInternalPhone:
			values[i] = new(sql.NullString)
		case employee.FieldBirthDate:
			values[i] = new(sql.NullTime)
		case employee.FieldID, employee.FieldClientID, employee.FieldDzoID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Employee fields.
func (_m *Employee) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case employee.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case employee.FieldClientID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value != nil {
				_m.ClientID = *value
			}
		case employee.FieldDzoID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field dzo_id", values[i])
			} else if value != nil {
				_m.DzoID = *value
			}
		case employee.FieldDzoPositionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field dzo_position_id", values[i])
			} else if value.Valid {
				_m.DzoPositionID = new(uuid.UUID)
				*_m.DzoPositionID = *value.S.(*uuid.UUID)
			}
		case employee.FieldFullName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field full_name", values[i])
			} else if value.Valid {
				_m.FullName = value.String
			}
		case employee.FieldShortName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field short_name", values[i])
			} else if value.Valid {
				_m.ShortName = new(string)
				*_m.ShortName = value.String
			}
		case employee.FieldDepartment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field department", values[i])
			} else if value.Valid {
				_m.Department = new(string)
				*_m.Department = value.String
			}
		case employee.FieldDirection:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field direction", values[i])
			} else if value.Valid {
				_m.Direction = new(string)
				*_m.Direction = value.String
			}
		case employee.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case employee.FieldInternalPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field internal_phone", values[i])
			} else if value.Valid {
				_m.InternalPhone = new(string)
				*_m.InternalPhone = value.String
			}
		case employee.FieldBirthDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field birth_date", values[i])
			} else if value.Valid {
				_m.BirthDate = new(time.Time)
				*_m.BirthDate = value.Time
			}
		case employee.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case employee.FieldUserID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(uuid.UUID)
				*_m.UserID = *value.S.(*uuid.UUID)
			}
		case employee.FieldIsDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_deleted", values[i])
			} else if value.Valid {
				_m.IsDeleted = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Employee.
// This includes values selected through modifiers, order, etc.
func (_m *Employee) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDzo queries the "dzo" edge of the Employee entity.
func (_m *Employee) QueryDzo() *DzoOrganizationQuery {
	return NewEmployeeClient(_m.config).QueryDzo(_m)
}

// QueryDzoPositionTitle queries the "dzo_position_title" edge of the Employee entity.
func (_m *Employee) QueryDzoPositionTitle() *DzoPositionTitleQuery {
	return NewEmployeeClient(_m.config).QueryDzoPositionTitle(_m)
}

// QueryEventParticipations queries the "event_participations" edge of the Employee entity.
func (_m *Employee) QueryEventParticipations() *EventParticipantQuery {
	return NewEmployeeClient(_m.config).QueryEventParticipations(_m)
}

// Update returns a builder for updating this Employee.
// Note that you need to call Employee.Unwrap() before calling this method if this Employee
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Employee) Update() *EmployeeUpdateOne {
	return NewEmployeeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Employee entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Employee) Unwrap() *Employee {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Employee is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Employee) String() string {
	var builder strings.Builder
	builder.WriteString("Employee(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("client_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientID))
	builder.WriteString(", ")
	builder.WriteString("dzo_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DzoID))
	builder.WriteString(", ")
	if v := _m.DzoPositionID; v != nil {
		builder.WriteString("dzo_position_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("full_name=")
	builder.WriteString(_m.FullName)
	builder.WriteString(", ")
	if v := _m.ShortName; v != nil {
		builder.WriteString("short_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Department; v != nil {
		builder.WriteString("department=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Direction; v != nil {
		builder.WriteString("direction=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	if v := _m.InternalPhone; v != nil {
		builder.WriteString("internal_phone=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.BirthDate; v != nil {
		builder.WriteString("birth_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("is_deleted=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDeleted))
	builder.WriteByte(')')
	return builder.String()
}

// Employees is a parsable slice of Employee.
type Employees []*Employee
