// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"encore.app/db/ent/externaltrainingevent"
	"encore.app/db/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExternalTrainingEventDelete is the builder for deleting a ExternalTrainingEvent entity.
type ExternalTrainingEventDelete struct {
	config
	hooks    []Hook
	mutation *ExternalTrainingEventMutation
}

// Where appends a list predicates to the ExternalTrainingEventDelete builder.
func (_d *ExternalTrainingEventDelete) Where(ps ...predicate.ExternalTrainingEvent) *ExternalTrainingEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ExternalTrainingEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExternalTrainingEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ExternalTrainingEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(externaltrainingevent.Table, sqlgraph.NewFieldSpec(externaltrainingevent.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ExternalTrainingEventDeleteOne is the builder for deleting a single ExternalTrainingEvent entity.
type ExternalTrainingEventDeleteOne struct {
	_d *ExternalTrainingEventDelete
}

// Where appends a list predicates to the ExternalTrainingEventDelete builder.
func (_d *ExternalTrainingEventDeleteOne) Where(ps ...predicate.ExternalTrainingEvent) *ExternalTrainingEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ExternalTrainingEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{externaltrainingevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ExternalTrainingEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
