// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"encore.app/db/ent/requesttargetdzo"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RequestTargetDzoCreate is the builder for creating a RequestTargetDzo entity.
type RequestTargetDzoCreate struct {
	config
	mutation *RequestTargetDzoMutation
	hooks    []Hook
}

// SetRequestID sets the "request_id" field.
func (_c *RequestTargetDzoCreate) SetRequestID(v uuid.UUID) *RequestTargetDzoCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetDzoID sets the "dzo_id" field.
func (_c *RequestTargetDzoCreate) SetDzoID(v uuid.UUID) *RequestTargetDzoCreate {
	_c.mutation.SetDzoID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestTargetDzoCreate) SetCreatedAt(v time.Time) *RequestTargetDzoCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequestTargetDzoCreate) SetNillableCreatedAt(v *time.Time) *RequestTargetDzoCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RequestTargetDzoCreate) SetID(v uuid.UUID) *RequestTargetDzoCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RequestTargetDzoCreate) SetNillableID(v *uuid.UUID) *RequestTargetDzoCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RequestTargetDzoMutation object of the builder.
func (_c *RequestTargetDzoCreate) Mutation() *RequestTargetDzoMutation {
	return _c.mutation
}

// Save creates the RequestTargetDzo in the database.
func (_c *RequestTargetDzoCreate) Save(ctx context.Context) (*RequestTargetDzo, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestTargetDzoCreate) SaveX(ctx context.Context) *RequestTargetDzo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestTargetDzoCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestTargetDzoCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestTargetDzoCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := requesttargetdzo.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := requesttargetdzo.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestTargetDzoCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "RequestTargetDzo.request_id"`)}
	}
	if _, ok := _c.mutation.DzoID(); !ok {
		return &ValidationError{Name: "dzo_id", err: errors.New(`ent: missing required field "RequestTargetDzo.dzo_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RequestTargetDzo.created_at"`)}
	}
	return nil
}

func (_c *RequestTargetDzoCreate) sqlSave(ctx context.Context) (*RequestTargetDzo, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestTargetDzoCreate) createSpec() (*RequestTargetDzo, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestTargetDzo{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requesttargetdzo.Table, sqlgraph.NewFieldSpec(requesttargetdzo.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(requesttargetdzo.FieldRequestID, field.TypeUUID, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.DzoID(); ok {
		_spec.SetField(requesttargetdzo.FieldDzoID, field.TypeUUID, value)
		_node.DzoID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(requesttargetdzo.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// RequestTargetDzoCreateBulk is the builder for creating many RequestTargetDzo entities in bulk.
type RequestTargetDzoCreateBulk struct {
	config
	err      error
	builders []*RequestTargetDzoCreate
}

// Save creates the RequestTargetDzo entities in the database.
func (_c *RequestTargetDzoCreateBulk) Save(ctx context.Context) ([]*RequestTargetDzo, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestTargetDzo, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestTargetDzoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestTargetDzoCreateBulk) SaveX(ctx context.Context) []*RequestTargetDzo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestTargetDzoCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestTargetDzoCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
