// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"encore.app/db/ent/requestemployee"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// RequestEmployee is the model entity for the RequestEmployee schema.
type RequestEmployee struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID uuid.UUID `json:"request_id,omitempty"`
	// EmployeeID holds the value of the "employee_id" field.
	EmployeeID uuid.UUID `json:"employee_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequestEmployee) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requestemployee.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case requestemployee.FieldID, requestemployee.FieldRequestID, requestemployee.FieldEmployeeID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequestEmployee fields.
func (_m *RequestEmployee) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requestemployee.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case requestemployee.FieldRequestID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value != nil {
				_m.RequestID = *value
			}
		case requestemployee.FieldEmployeeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field employee_id", values[i])
			} else if value != nil {
				_m.EmployeeID = *value
			}
		case requestemployee.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RequestEmployee.
// This includes values selected through modifiers, order, etc.
func (_m *RequestEmployee) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RequestEmployee.
// Note that you need to call RequestEmployee.Unwrap() before calling this method if this RequestEmployee
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RequestEmployee) Update() *RequestEmployeeUpdateOne {
	return NewRequestEmployeeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RequestEmployee entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RequestEmployee) Unwrap() *RequestEmployee {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequestEmployee is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RequestEmployee) String() string {
	var builder strings.Builder
	builder.WriteString("RequestEmployee(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestID))
	builder.WriteString(", ")
	builder.WriteString("employee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmployeeID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RequestEmployees is a parsable slice of RequestEmployee.
type RequestEmployees []*RequestEmployee
