// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"encore.app/db/ent/predicate"
	"encore.app/db/ent/request"
	"encore.app/db/ent/user"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RequestUpdate is the builder for updating Request entities.
type RequestUpdate struct {
	config
	hooks    []Hook
	mutation *RequestMutation
}

// Where appends a list predicates to the RequestUpdate builder.
func (_u *RequestUpdate) Where(ps ...predicate.Request) *RequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInitiatorID sets the "initiator_id" field.
func (_u *RequestUpdate) SetInitiatorID(v uuid.UUID) *RequestUpdate {
	_u.mutation.SetInitiatorID(v)
	return _u
}

// SetNillableInitiatorID sets the "initiator_id" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableInitiatorID(v *uuid.UUID) *RequestUpdate {
	if v != nil {
		_u.SetInitiatorID(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *RequestUpdate) SetEntityID(v uuid.UUID) *RequestUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableEntityID(v *uuid.UUID) *RequestUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *RequestUpdate) SetEntityType(v string) *RequestUpdate {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableEntityType(v *string) *RequestUpdate {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetStep sets the "step" field.
func (_u *RequestUpdate) SetStep(v int) *RequestUpdate {
	_u.mutation.ResetStep()
	_u.mutation.SetStep(v)
	return _u
}

// SetNillableStep sets the "step" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableStep(v *int) *RequestUpdate {
	if v != nil {
		_u.SetStep(*v)
	}
	return _u
}

// AddStep adds value to the "step" field.
func (_u *RequestUpdate) AddStep(v int) *RequestUpdate {
	_u.mutation.AddStep(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RequestUpdate) SetCreatedAt(v time.Time) *RequestUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableCreatedAt(v *time.Time) *RequestUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RequestUpdate) SetStatus(v string) *RequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableStatus(v *string) *RequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInitiator sets the "initiator" edge to the User entity.
func (_u *RequestUpdate) SetInitiator(v *User) *RequestUpdate {
	return _u.SetInitiatorID(v.ID)
}

// Mutation returns the RequestMutation object of the builder.
func (_u *RequestUpdate) Mutation() *RequestMutation {
	return _u.mutation
}

// ClearInitiator clears the "initiator" edge to the User entity.
func (_u *RequestUpdate) ClearInitiator() *RequestUpdate {
	_u.mutation.ClearInitiator()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestUpdate) check() error {
	if _u.mutation.InitiatorCleared() && len(_u.mutation.InitiatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Request.initiator"`)
	}
	return nil
}

func (_u *RequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(request.Table, request.Columns, sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(request.FieldEntityID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(request.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Step(); ok {
		_spec.SetField(request.FieldStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStep(); ok {
		_spec.AddField(request.FieldStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(request.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(request.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.InitiatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.InitiatorTable,
			Columns: []string{request.InitiatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InitiatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.InitiatorTable,
			Columns: []string{request.InitiatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{request.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestUpdateOne is the builder for updating a single Request entity.
type RequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestMutation
}

// SetInitiatorID sets the "initiator_id" field.
func (_u *RequestUpdateOne) SetInitiatorID(v uuid.UUID) *RequestUpdateOne {
	_u.mutation.SetInitiatorID(v)
	return _u
}

// SetNillableInitiatorID sets the "initiator_id" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableInitiatorID(v *uuid.UUID) *RequestUpdateOne {
	if v != nil {
		_u.SetInitiatorID(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *RequestUpdateOne) SetEntityID(v uuid.UUID) *RequestUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableEntityID(v *uuid.UUID) *RequestUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// SetEntityType sets the "entity_type" field.
func (_u *RequestUpdateOne) SetEntityType(v string) *RequestUpdateOne {
	_u.mutation.SetEntityType(v)
	return _u
}

// SetNillableEntityType sets the "entity_type" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableEntityType(v *string) *RequestUpdateOne {
	if v != nil {
		_u.SetEntityType(*v)
	}
	return _u
}

// SetStep sets the "step" field.
func (_u *RequestUpdateOne) SetStep(v int) *RequestUpdateOne {
	_u.mutation.ResetStep()
	_u.mutation.SetStep(v)
	return _u
}

// SetNillableStep sets the "step" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableStep(v *int) *RequestUpdateOne {
	if v != nil {
		_u.SetStep(*v)
	}
	return _u
}

// AddStep adds value to the "step" field.
func (_u *RequestUpdateOne) AddStep(v int) *RequestUpdateOne {
	_u.mutation.AddStep(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RequestUpdateOne) SetCreatedAt(v time.Time) *RequestUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableCreatedAt(v *time.Time) *RequestUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RequestUpdateOne) SetStatus(v string) *RequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableStatus(v *string) *RequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInitiator sets the "initiator" edge to the User entity.
func (_u *RequestUpdateOne) SetInitiator(v *User) *RequestUpdateOne {
	return _u.SetInitiatorID(v.ID)
}

// Mutation returns the RequestMutation object of the builder.
func (_u *RequestUpdateOne) Mutation() *RequestMutation {
	return _u.mutation
}

// ClearInitiator clears the "initiator" edge to the User entity.
func (_u *RequestUpdateOne) ClearInitiator() *RequestUpdateOne {
	_u.mutation.ClearInitiator()
	return _u
}

// Where appends a list predicates to the RequestUpdate builder.
func (_u *RequestUpdateOne) Where(ps ...predicate.Request) *RequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestUpdateOne) Select(field string, fields ...string) *RequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Request entity.
func (_u *RequestUpdateOne) Save(ctx context.Context) (*Request, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestUpdateOne) SaveX(ctx context.Context) *Request {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestUpdateOne) check() error {
	if _u.mutation.InitiatorCleared() && len(_u.mutation.InitiatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Request.initiator"`)
	}
	return nil
}

func (_u *RequestUpdateOne) sqlSave(ctx context.Context) (_node *Request, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(request.Table, request.Columns, sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Request.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, request.FieldID)
		for _, f := range fields {
			if !request.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != request.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(request.FieldEntityID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.EntityType(); ok {
		_spec.SetField(request.FieldEntityType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Step(); ok {
		_spec.SetField(request.FieldStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStep(); ok {
		_spec.AddField(request.FieldStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(request.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(request.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.InitiatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.InitiatorTable,
			Columns: []string{request.InitiatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InitiatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.InitiatorTable,
			Columns: []string{request.InitiatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Request{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{request.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
