// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"encore.app/db/ent/scormcourse"
	"encore.app/db/ent/scormprogress"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ScormProgress is the model entity for the ScormProgress schema.
type ScormProgress struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CourseID holds the value of the "course_id" field.
	CourseID uuid.UUID `json:"course_id,omitempty"`
	// EmployeeID holds the value of the "employee_id" field.
	EmployeeID uuid.UUID `json:"employee_id,omitempty"`
	// Status holds the value of the "status" field.
	Status scormprogress.Status `json:"status,omitempty"`
	// Score holds the value of the "score" field.
	Score *int `json:"score,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// SuspendData holds the value of the "suspend_data" field.
	SuspendData *string `json:"suspend_data,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ScormProgressQuery when eager-loading is set.
	Edges        ScormProgressEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ScormProgressEdges holds the relations/edges for other nodes in the graph.
type ScormProgressEdges struct {
	// Progress holds the value of the progress edge.
	Progress *ScormCourse `json:"progress,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProgressOrErr returns the Progress value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScormProgressEdges) ProgressOrErr() (*ScormCourse, error) {
	if e.Progress != nil {
		return e.Progress, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: scormcourse.Label}
	}
	return nil, &NotLoadedError{edge: "progress"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScormProgress) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case scormprogress.FieldScore:
			values[i] = new(sql.NullInt64)
		case scormprogress.FieldStatus, scormprogress.FieldSuspendData:
			values[i] = new(sql.NullString)
		case scormprogress.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case scormprogress.FieldID, scormprogress.FieldCourseID, scormprogress.FieldEmployeeID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScormProgress fields.
func (_m *ScormProgress) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case scormprogress.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case scormprogress.FieldCourseID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field course_id", values[i])
			} else if value != nil {
				_m.CourseID = *value
			}
		case scormprogress.FieldEmployeeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field employee_id", values[i])
			} else if value != nil {
				_m.EmployeeID = *value
			}
		case scormprogress.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = scormprogress.Status(value.String)
			}
		case scormprogress.FieldScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = new(int)
				*_m.Score = int(value.Int64)
			}
		case scormprogress.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case scormprogress.FieldSuspendData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field suspend_data", values[i])
			} else if value.Valid {
				_m.SuspendData = new(string)
				*_m.SuspendData = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScormProgress.
// This includes values selected through modifiers, order, etc.
func (_m *ScormProgress) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProgress queries the "progress" edge of the ScormProgress entity.
func (_m *ScormProgress) QueryProgress() *ScormCourseQuery {
	return NewScormProgressClient(_m.config).QueryProgress(_m)
}

// Update returns a builder for updating this ScormProgress.
// Note that you need to call ScormProgress.Unwrap() before calling this method if this ScormProgress
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ScormProgress) Update() *ScormProgressUpdateOne {
	return NewScormProgressClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ScormProgress entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ScormProgress) Unwrap() *ScormProgress {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScormProgress is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ScormProgress) String() string {
	var builder strings.Builder
	builder.WriteString("ScormProgress(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("course_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CourseID))
	builder.WriteString(", ")
	builder.WriteString("employee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmployeeID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.Score; v != nil {
		builder.WriteString("score=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SuspendData; v != nil {
		builder.WriteString("suspend_data=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ScormProgresses is a parsable slice of ScormProgress.
type ScormProgresses []*ScormProgress
