// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"encore.app/db/ent/predicate"
	"encore.app/db/ent/trainingparticipant"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TrainingParticipantDelete is the builder for deleting a TrainingParticipant entity.
type TrainingParticipantDelete struct {
	config
	hooks    []Hook
	mutation *TrainingParticipantMutation
}

// Where appends a list predicates to the TrainingParticipantDelete builder.
func (_d *TrainingParticipantDelete) Where(ps ...predicate.TrainingParticipant) *TrainingParticipantDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TrainingParticipantDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TrainingParticipantDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TrainingParticipantDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(trainingparticipant.Table, sqlgraph.NewFieldSpec(trainingparticipant.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TrainingParticipantDeleteOne is the builder for deleting a single TrainingParticipant entity.
type TrainingParticipantDeleteOne struct {
	_d *TrainingParticipantDelete
}

// Where appends a list predicates to the TrainingParticipantDelete builder.
func (_d *TrainingParticipantDeleteOne) Where(ps ...predicate.TrainingParticipant) *TrainingParticipantDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TrainingParticipantDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{trainingparticipant.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TrainingParticipantDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
