// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"encore.app/db/ent/company"
	"encore.app/db/ent/event"
	"encore.app/db/ent/eventparticipant"
	"encore.app/db/ent/externaltrainingevent"
	"encore.app/db/ent/predicate"
	"encore.app/db/ent/request"
	"encore.app/db/ent/user"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKeycloakUserID sets the "keycloak_user_id" field.
func (_u *UserUpdate) SetKeycloakUserID(v string) *UserUpdate {
	_u.mutation.SetKeycloakUserID(v)
	return _u
}

// SetNillableKeycloakUserID sets the "keycloak_user_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableKeycloakUserID(v *string) *UserUpdate {
	if v != nil {
		_u.SetKeycloakUserID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *UserUpdate) SetRole(v string) *UserUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *UserUpdate) SetNillableRole(v *string) *UserUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetDzoID sets the "dzo_id" field.
func (_u *UserUpdate) SetDzoID(v uuid.UUID) *UserUpdate {
	_u.mutation.SetDzoID(v)
	return _u
}

// SetNillableDzoID sets the "dzo_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDzoID(v *uuid.UUID) *UserUpdate {
	if v != nil {
		_u.SetDzoID(*v)
	}
	return _u
}

// ClearDzoID clears the value of the "dzo_id" field.
func (_u *UserUpdate) ClearDzoID() *UserUpdate {
	_u.mutation.ClearDzoID()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserUpdate) SetIsActive(v bool) *UserUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsActive(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetIsOnboarded sets the "is_onboarded" field.
func (_u *UserUpdate) SetIsOnboarded(v bool) *UserUpdate {
	_u.mutation.SetIsOnboarded(v)
	return _u
}

// SetNillableIsOnboarded sets the "is_onboarded" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsOnboarded(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsOnboarded(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *UserUpdate) SetClientID(v uuid.UUID) *UserUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableClientID(v *uuid.UUID) *UserUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *UserUpdate) ClearClientID() *UserUpdate {
	_u.mutation.ClearClientID()
	return _u
}

// SetClient sets the "client" edge to the Company entity.
func (_u *UserUpdate) SetClient(v *Company) *UserUpdate {
	return _u.SetClientID(v.ID)
}

// AddRequestIDs adds the "requests" edge to the Request entity by IDs.
func (_u *UserUpdate) AddRequestIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddRequestIDs(ids...)
	return _u
}

// AddRequests adds the "requests" edges to the Request entity.
func (_u *UserUpdate) AddRequests(v ...*Request) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestIDs(ids...)
}

// AddHostedEventIDs adds the "hosted_events" edge to the Event entity by IDs.
func (_u *UserUpdate) AddHostedEventIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddHostedEventIDs(ids...)
	return _u
}

// AddHostedEvents adds the "hosted_events" edges to the Event entity.
func (_u *UserUpdate) AddHostedEvents(v ...*Event) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHostedEventIDs(ids...)
}

// AddReviewedParticipationIDs adds the "reviewed_participations" edge to the EventParticipant entity by IDs.
func (_u *UserUpdate) AddReviewedParticipationIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddReviewedParticipationIDs(ids...)
	return _u
}

// AddReviewedParticipations adds the "reviewed_participations" edges to the EventParticipant entity.
func (_u *UserUpdate) AddReviewedParticipations(v ...*EventParticipant) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewedParticipationIDs(ids...)
}

// AddResponsibleExternalTrainingEventIDs adds the "responsible_external_training_events" edge to the ExternalTrainingEvent entity by IDs.
func (_u *UserUpdate) AddResponsibleExternalTrainingEventIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddResponsibleExternalTrainingEventIDs(ids...)
	return _u
}

// AddResponsibleExternalTrainingEvents adds the "responsible_external_training_events" edges to the ExternalTrainingEvent entity.
func (_u *UserUpdate) AddResponsibleExternalTrainingEvents(v ...*ExternalTrainingEvent) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResponsibleExternalTrainingEventIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearClient clears the "client" edge to the Company entity.
func (_u *UserUpdate) ClearClient() *UserUpdate {
	_u.mutation.ClearClient()
	return _u
}

// ClearRequests clears all "requests" edges to the Request entity.
func (_u *UserUpdate) ClearRequests() *UserUpdate {
	_u.mutation.ClearRequests()
	return _u
}

// RemoveRequestIDs removes the "requests" edge to Request entities by IDs.
func (_u *UserUpdate) RemoveRequestIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveRequestIDs(ids...)
	return _u
}

// RemoveRequests removes "requests" edges to Request entities.
func (_u *UserUpdate) RemoveRequests(v ...*Request) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestIDs(ids...)
}

// ClearHostedEvents clears all "hosted_events" edges to the Event entity.
func (_u *UserUpdate) ClearHostedEvents() *UserUpdate {
	_u.mutation.ClearHostedEvents()
	return _u
}

// RemoveHostedEventIDs removes the "hosted_events" edge to Event entities by IDs.
func (_u *UserUpdate) RemoveHostedEventIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveHostedEventIDs(ids...)
	return _u
}

// RemoveHostedEvents removes "hosted_events" edges to Event entities.
func (_u *UserUpdate) RemoveHostedEvents(v ...*Event) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHostedEventIDs(ids...)
}

// ClearReviewedParticipations clears all "reviewed_participations" edges to the EventParticipant entity.
func (_u *UserUpdate) ClearReviewedParticipations() *UserUpdate {
	_u.mutation.ClearReviewedParticipations()
	return _u
}

// RemoveReviewedParticipationIDs removes the "reviewed_participations" edge to EventParticipant entities by IDs.
func (_u *UserUpdate) RemoveReviewedParticipationIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveReviewedParticipationIDs(ids...)
	return _u
}

// RemoveReviewedParticipations removes "reviewed_participations" edges to EventParticipant entities.
func (_u *UserUpdate) RemoveReviewedParticipations(v ...*EventParticipant) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewedParticipationIDs(ids...)
}

// ClearResponsibleExternalTrainingEvents clears all "responsible_external_training_events" edges to the ExternalTrainingEvent entity.
func (_u *UserUpdate) ClearResponsibleExternalTrainingEvents() *UserUpdate {
	_u.mutation.ClearResponsibleExternalTrainingEvents()
	return _u
}

// RemoveResponsibleExternalTrainingEventIDs removes the "responsible_external_training_events" edge to ExternalTrainingEvent entities by IDs.
func (_u *UserUpdate) RemoveResponsibleExternalTrainingEventIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveResponsibleExternalTrainingEventIDs(ids...)
	return _u
}

// RemoveResponsibleExternalTrainingEvents removes "responsible_external_training_events" edges to ExternalTrainingEvent entities.
func (_u *UserUpdate) RemoveResponsibleExternalTrainingEvents(v ...*ExternalTrainingEvent) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResponsibleExternalTrainingEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.KeycloakUserID(); ok {
		if err := user.KeycloakUserIDValidator(v); err != nil {
			return &ValidationError{Name: "keycloak_user_id", err: fmt.Errorf(`ent: validator failed for field "User.keycloak_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := user.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "User.role": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.KeycloakUserID(); ok {
		_spec.SetField(user.FieldKeycloakUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(user.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.DzoID(); ok {
		_spec.SetField(user.FieldDzoID, field.TypeUUID, value)
	}
	if _u.mutation.DzoIDCleared() {
		_spec.ClearField(user.FieldDzoID, field.TypeUUID)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(user.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsOnboarded(); ok {
		_spec.SetField(user.FieldIsOnboarded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.ClientTable,
			Columns: []string{user.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.ClientTable,
			Columns: []string{user.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RequestsTable,
			Columns: []string{user.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestsIDs(); len(nodes) > 0 && !_u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RequestsTable,
			Columns: []string{user.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RequestsTable,
			Columns: []string{user.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HostedEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.HostedEventsTable,
			Columns: []string{user.HostedEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHostedEventsIDs(); len(nodes) > 0 && !_u.mutation.HostedEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.HostedEventsTable,
			Columns: []string{user.HostedEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HostedEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.HostedEventsTable,
			Columns: []string{user.HostedEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewedParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewedParticipationsTable,
			Columns: []string{user.ReviewedParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventparticipant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewedParticipationsIDs(); len(nodes) > 0 && !_u.mutation.ReviewedParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewedParticipationsTable,
			Columns: []string{user.ReviewedParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewedParticipationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewedParticipationsTable,
			Columns: []string{user.ReviewedParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResponsibleExternalTrainingEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ResponsibleExternalTrainingEventsTable,
			Columns: []string{user.ResponsibleExternalTrainingEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externaltrainingevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResponsibleExternalTrainingEventsIDs(); len(nodes) > 0 && !_u.mutation.ResponsibleExternalTrainingEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ResponsibleExternalTrainingEventsTable,
			Columns: []string{user.ResponsibleExternalTrainingEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externaltrainingevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResponsibleExternalTrainingEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ResponsibleExternalTrainingEventsTable,
			Columns: []string{user.ResponsibleExternalTrainingEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externaltrainingevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetKeycloakUserID sets the "keycloak_user_id" field.
func (_u *UserUpdateOne) SetKeycloakUserID(v string) *UserUpdateOne {
	_u.mutation.SetKeycloakUserID(v)
	return _u
}

// SetNillableKeycloakUserID sets the "keycloak_user_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableKeycloakUserID(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetKeycloakUserID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *UserUpdateOne) SetRole(v string) *UserUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableRole(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetDzoID sets the "dzo_id" field.
func (_u *UserUpdateOne) SetDzoID(v uuid.UUID) *UserUpdateOne {
	_u.mutation.SetDzoID(v)
	return _u
}

// SetNillableDzoID sets the "dzo_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDzoID(v *uuid.UUID) *UserUpdateOne {
	if v != nil {
		_u.SetDzoID(*v)
	}
	return _u
}

// ClearDzoID clears the value of the "dzo_id" field.
func (_u *UserUpdateOne) ClearDzoID() *UserUpdateOne {
	_u.mutation.ClearDzoID()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserUpdateOne) SetIsActive(v bool) *UserUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsActive(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetIsOnboarded sets the "is_onboarded" field.
func (_u *UserUpdateOne) SetIsOnboarded(v bool) *UserUpdateOne {
	_u.mutation.SetIsOnboarded(v)
	return _u
}

// SetNillableIsOnboarded sets the "is_onboarded" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsOnboarded(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsOnboarded(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *UserUpdateOne) SetClientID(v uuid.UUID) *UserUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableClientID(v *uuid.UUID) *UserUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *UserUpdateOne) ClearClientID() *UserUpdateOne {
	_u.mutation.ClearClientID()
	return _u
}

// SetClient sets the "client" edge to the Company entity.
func (_u *UserUpdateOne) SetClient(v *Company) *UserUpdateOne {
	return _u.SetClientID(v.ID)
}

// AddRequestIDs adds the "requests" edge to the Request entity by IDs.
func (_u *UserUpdateOne) AddRequestIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddRequestIDs(ids...)
	return _u
}

// AddRequests adds the "requests" edges to the Request entity.
func (_u *UserUpdateOne) AddRequests(v ...*Request) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestIDs(ids...)
}

// AddHostedEventIDs adds the "hosted_events" edge to the Event entity by IDs.
func (_u *UserUpdateOne) AddHostedEventIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddHostedEventIDs(ids...)
	return _u
}

// AddHostedEvents adds the "hosted_events" edges to the Event entity.
func (_u *UserUpdateOne) AddHostedEvents(v ...*Event) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHostedEventIDs(ids...)
}

// AddReviewedParticipationIDs adds the "reviewed_participations" edge to the EventParticipant entity by IDs.
func (_u *UserUpdateOne) AddReviewedParticipationIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddReviewedParticipationIDs(ids...)
	return _u
}

// AddReviewedParticipations adds the "reviewed_participations" edges to the EventParticipant entity.
func (_u *UserUpdateOne) AddReviewedParticipations(v ...*EventParticipant) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddReviewedParticipationIDs(ids...)
}

// AddResponsibleExternalTrainingEventIDs adds the "responsible_external_training_events" edge to the ExternalTrainingEvent entity by IDs.
func (_u *UserUpdateOne) AddResponsibleExternalTrainingEventIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddResponsibleExternalTrainingEventIDs(ids...)
	return _u
}

// AddResponsibleExternalTrainingEvents adds the "responsible_external_training_events" edges to the ExternalTrainingEvent entity.
func (_u *UserUpdateOne) AddResponsibleExternalTrainingEvents(v ...*ExternalTrainingEvent) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddResponsibleExternalTrainingEventIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearClient clears the "client" edge to the Company entity.
func (_u *UserUpdateOne) ClearClient() *UserUpdateOne {
	_u.mutation.ClearClient()
	return _u
}

// ClearRequests clears all "requests" edges to the Request entity.
func (_u *UserUpdateOne) ClearRequests() *UserUpdateOne {
	_u.mutation.ClearRequests()
	return _u
}

// RemoveRequestIDs removes the "requests" edge to Request entities by IDs.
func (_u *UserUpdateOne) RemoveRequestIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveRequestIDs(ids...)
	return _u
}

// RemoveRequests removes "requests" edges to Request entities.
func (_u *UserUpdateOne) RemoveRequests(v ...*Request) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestIDs(ids...)
}

// ClearHostedEvents clears all "hosted_events" edges to the Event entity.
func (_u *UserUpdateOne) ClearHostedEvents() *UserUpdateOne {
	_u.mutation.ClearHostedEvents()
	return _u
}

// RemoveHostedEventIDs removes the "hosted_events" edge to Event entities by IDs.
func (_u *UserUpdateOne) RemoveHostedEventIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveHostedEventIDs(ids...)
	return _u
}

// RemoveHostedEvents removes "hosted_events" edges to Event entities.
func (_u *UserUpdateOne) RemoveHostedEvents(v ...*Event) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHostedEventIDs(ids...)
}

// ClearReviewedParticipations clears all "reviewed_participations" edges to the EventParticipant entity.
func (_u *UserUpdateOne) ClearReviewedParticipations() *UserUpdateOne {
	_u.mutation.ClearReviewedParticipations()
	return _u
}

// RemoveReviewedParticipationIDs removes the "reviewed_participations" edge to EventParticipant entities by IDs.
func (_u *UserUpdateOne) RemoveReviewedParticipationIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveReviewedParticipationIDs(ids...)
	return _u
}

// RemoveReviewedParticipations removes "reviewed_participations" edges to EventParticipant entities.
func (_u *UserUpdateOne) RemoveReviewedParticipations(v ...*EventParticipant) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveReviewedParticipationIDs(ids...)
}

// ClearResponsibleExternalTrainingEvents clears all "responsible_external_training_events" edges to the ExternalTrainingEvent entity.
func (_u *UserUpdateOne) ClearResponsibleExternalTrainingEvents() *UserUpdateOne {
	_u.mutation.ClearResponsibleExternalTrainingEvents()
	return _u
}

// RemoveResponsibleExternalTrainingEventIDs removes the "responsible_external_training_events" edge to ExternalTrainingEvent entities by IDs.
func (_u *UserUpdateOne) RemoveResponsibleExternalTrainingEventIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveResponsibleExternalTrainingEventIDs(ids...)
	return _u
}

// RemoveResponsibleExternalTrainingEvents removes "responsible_external_training_events" edges to ExternalTrainingEvent entities.
func (_u *UserUpdateOne) RemoveResponsibleExternalTrainingEvents(v ...*ExternalTrainingEvent) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveResponsibleExternalTrainingEventIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.KeycloakUserID(); ok {
		if err := user.KeycloakUserIDValidator(v); err != nil {
			return &ValidationError{Name: "keycloak_user_id", err: fmt.Errorf(`ent: validator failed for field "User.keycloak_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := user.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "User.role": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.KeycloakUserID(); ok {
		_spec.SetField(user.FieldKeycloakUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(user.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.DzoID(); ok {
		_spec.SetField(user.FieldDzoID, field.TypeUUID, value)
	}
	if _u.mutation.DzoIDCleared() {
		_spec.ClearField(user.FieldDzoID, field.TypeUUID)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(user.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsOnboarded(); ok {
		_spec.SetField(user.FieldIsOnboarded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.ClientTable,
			Columns: []string{user.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.ClientTable,
			Columns: []string{user.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(company.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RequestsTable,
			Columns: []string{user.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestsIDs(); len(nodes) > 0 && !_u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RequestsTable,
			Columns: []string{user.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RequestsTable,
			Columns: []string{user.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HostedEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.HostedEventsTable,
			Columns: []string{user.HostedEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHostedEventsIDs(); len(nodes) > 0 && !_u.mutation.HostedEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.HostedEventsTable,
			Columns: []string{user.HostedEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HostedEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.HostedEventsTable,
			Columns: []string{user.HostedEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewedParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewedParticipationsTable,
			Columns: []string{user.ReviewedParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventparticipant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedReviewedParticipationsIDs(); len(nodes) > 0 && !_u.mutation.ReviewedParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewedParticipationsTable,
			Columns: []string{user.ReviewedParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewedParticipationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ReviewedParticipationsTable,
			Columns: []string{user.ReviewedParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(eventparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResponsibleExternalTrainingEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ResponsibleExternalTrainingEventsTable,
			Columns: []string{user.ResponsibleExternalTrainingEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externaltrainingevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedResponsibleExternalTrainingEventsIDs(); len(nodes) > 0 && !_u.mutation.ResponsibleExternalTrainingEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ResponsibleExternalTrainingEventsTable,
			Columns: []string{user.ResponsibleExternalTrainingEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externaltrainingevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResponsibleExternalTrainingEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ResponsibleExternalTrainingEventsTable,
			Columns: []string{user.ResponsibleExternalTrainingEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(externaltrainingevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
