// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"encore.app/db/ent/company"
	"encore.app/db/ent/user"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Keycloak subject (sub claim)
	KeycloakUserID string `json:"keycloak_user_id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Business role: SA, ADM, HR, EMP
	Role string `json:"role,omitempty"`
	// DZO organization reference (from Keycloak dzoId claim)
	DzoID *uuid.UUID `json:"dzo_id,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// True once the user has completed onboarding (first login after SA registration). Pending admins created via RegisterAdmin start as false and are auto-activated on first login.
	IsOnboarded bool `json:"is_onboarded,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Reference to clients.id
	ClientID uuid.UUID `json:"client_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Client holds the value of the client edge.
	Client *Company `json:"client,omitempty"`
	// Requests holds the value of the requests edge.
	Requests []*Request `json:"requests,omitempty"`
	// HostedEvents holds the value of the hosted_events edge.
	HostedEvents []*Event `json:"hosted_events,omitempty"`
	// ReviewedParticipations holds the value of the reviewed_participations edge.
	ReviewedParticipations []*EventParticipant `json:"reviewed_participations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// ClientOrErr returns the Client value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) ClientOrErr() (*Company, error) {
	if e.Client != nil {
		return e.Client, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: company.Label}
	}
	return nil, &NotLoadedError{edge: "client"}
}

// RequestsOrErr returns the Requests value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) RequestsOrErr() ([]*Request, error) {
	if e.loadedTypes[1] {
		return e.Requests, nil
	}
	return nil, &NotLoadedError{edge: "requests"}
}

// HostedEventsOrErr returns the HostedEvents value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) HostedEventsOrErr() ([]*Event, error) {
	if e.loadedTypes[2] {
		return e.HostedEvents, nil
	}
	return nil, &NotLoadedError{edge: "hosted_events"}
}

// ReviewedParticipationsOrErr returns the ReviewedParticipations value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ReviewedParticipationsOrErr() ([]*EventParticipant, error) {
	if e.loadedTypes[3] {
		return e.ReviewedParticipations, nil
	}
	return nil, &NotLoadedError{edge: "reviewed_participations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldDzoID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case user.FieldIsActive, user.FieldIsOnboarded:
			values[i] = new(sql.NullBool)
		case user.FieldKeycloakUserID, user.FieldEmail, user.FieldRole:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case user.FieldID, user.FieldClientID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case user.FieldKeycloakUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field keycloak_user_id", values[i])
			} else if value.Valid {
				_m.KeycloakUserID = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case user.FieldDzoID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field dzo_id", values[i])
			} else if value.Valid {
				_m.DzoID = new(uuid.UUID)
				*_m.DzoID = *value.S.(*uuid.UUID)
			}
		case user.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case user.FieldIsOnboarded:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_onboarded", values[i])
			} else if value.Valid {
				_m.IsOnboarded = value.Bool
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case user.FieldClientID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value != nil {
				_m.ClientID = *value
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryClient queries the "client" edge of the User entity.
func (_m *User) QueryClient() *CompanyQuery {
	return NewUserClient(_m.config).QueryClient(_m)
}

// QueryRequests queries the "requests" edge of the User entity.
func (_m *User) QueryRequests() *RequestQuery {
	return NewUserClient(_m.config).QueryRequests(_m)
}

// QueryHostedEvents queries the "hosted_events" edge of the User entity.
func (_m *User) QueryHostedEvents() *EventQuery {
	return NewUserClient(_m.config).QueryHostedEvents(_m)
}

// QueryReviewedParticipations queries the "reviewed_participations" edge of the User entity.
func (_m *User) QueryReviewedParticipations() *EventParticipantQuery {
	return NewUserClient(_m.config).QueryReviewedParticipations(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("keycloak_user_id=")
	builder.WriteString(_m.KeycloakUserID)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	if v := _m.DzoID; v != nil {
		builder.WriteString("dzo_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("is_onboarded=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsOnboarded))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientID))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
